"""This module defines the register map for THZ firmware version 206."""

_TEMP = {
    "unit": "°C",
    "device_class": "temperature",
    "state_class": "measurement",
    "icon": "mdi:thermometer",
}
_FAN_POWER = {
    "unit": "%",
    "state_class": "measurement",
    "icon": "mdi:fan",
}
_SPEED = {
    "unit": "Hz",
    "device_class": "frequency",
    "state_class": "measurement",
    "icon": "mdi:speedometer",
}
_PRESSURE = {
    "unit": "bar",
    "device_class": "pressure",
    "state_class": "measurement",
    "icon": "mdi:gauge",
}
_HUMIDITY = {
    "unit": "%",
    "device_class": "humidity",
    "state_class": "measurement",
    "icon": "mdi:water-percent",
}
_POWER = {
    "unit": "W",
    "device_class": "power",
    "state_class": "measurement",
    "icon": "mdi:flash",
}

REGISTER_MAP = {
    "firmware": "206",
    "pxx01": [
        ("p37Fanstage1AirflowInlet: ", 4, 4, "hex", 1, {"translation_key": "fan_stage1_airflow_inlet"}),
        (" p38Fanstage2AirflowInlet: ", 8, 4, "hex", 1, {"translation_key": "fan_stage2_airflow_inlet"}),
        (" p39Fanstage3AirflowInlet: ", 12, 4, "hex", 1, {"translation_key": "fan_stage3_airflow_inlet"}),
        (" p40Fanstage1AirflowOutlet: ", 16, 4, "hex", 1, {"translation_key": "fan_stage1_airflow_outlet"}),
        (" p41Fanstage2AirflowOutlet: ", 20, 4, "hex", 1, {"translation_key": "fan_stage2_airflow_outlet"}),
        (" p42Fanstage3AirflowOutlet: ", 24, 4, "hex", 1, {"translation_key": "fan_stage3_airflow_outlet"}),
        (" p43UnschedVent3: ", 28, 4, "hex", 1, {"translation_key": "unsched_vent_3"}),
        (" p44UnschedVent2: ", 32, 4, "hex", 1, {"translation_key": "unsched_vent_2"}),
        (" p45UnschedVent1: ", 36, 4, "hex", 1, {"translation_key": "unsched_vent_1"}),
        (" p46UnschedVent0: ", 40, 4, "hex", 1, {"translation_key": "unsched_vent_0"}),
        (" p75PassiveCooling: ", 44, 4, "hex", 1, {"translation_key": "passive_cooling"}),
    ],
    "pxx03": [
        ("UpTempLimitDefrostEvaporatorEnd: ", 4, 4, "hex", 10, {"translation_key": "up_temp_limit_defrost_evaporator_end"}),
        (" MaxTimeDefrostEvaporator: ", 8, 4, "hex", 1, {"translation_key": "max_time_defrost_evaporator"}),
        (" LimitTempCondenserElectBoost: ", 12, 4, "hex", 10, {"translation_key": "limit_temp_condenser_elect_boost"}),
        (" LimitTempCondenserDefrostTerm: ", 16, 4, "hex", 10, {"translation_key": "limit_temp_condenser_defrost_term"}),
        (" p47CompressorRestartDelay: ", 20, 2, "hex", 1, {"translation_key": "compressor_restart_delay"}),
        (" p48MainFanSpeed: ", 22, 2, "hex", 1, {"translation_key": "main_fan_speed"}),
    ],
    "pxx04": [
        ("MaxDefrostDurationAAExchenger: ", 4, 2, "hex", 1, {"translation_key": "max_defrost_duration_aa_exchenger"}),
        (" DefrostStartThreshold: ", 6, 4, "hex", 10, {"translation_key": "defrost_start_threshold"}),
        (" VolumeFlowFilterReplacement: ", 10, 4, "hex", 1, {"translation_key": "volume_flow_filter_replacement"}),
    ],
    "pxx05": [
        ("p13GradientHC1: ", 4, 4, "hex", 10, {"translation_key": "gradient_hc1"}),
        (" p14LowEndHC1: ", 8, 4, "hex", 10, {"translation_key": "low_end_hc1"}),
        (" p15RoomInfluenceHC1: ", 12, 2, "hex", 10, {"translation_key": "room_influence_hc1"}),
        (" p16GradientHC2: ", 14, 4, "hex", 10, {"translation_key": "gradient_hc2"}),
        (" p17LowEndHC2: ", 18, 4, "hex", 10, {"translation_key": "low_end_hc2"}),
        (" p18RoomInfluenceHC2: ", 22, 2, "hex", 10, {"translation_key": "room_influence_hc2"}),
        (" p19FlowProportionHC1: ", 24, 4, "hex", 1, {"translation_key": "flow_proportion_hc1"}),
        (" p20FlowProportionHC2: ", 28, 4, "hex", 1, {"translation_key": "flow_proportion_hc2"}),
        (" MaxSetHeatFlowTempHC1: ", 32, 4, "hex", 10, {"translation_key": "max_set_heat_flow_temp_hc1"}),
        (" MinSetHeatFlowTempHC1: ", 36, 4, "hex", 10, {"translation_key": "min_set_heat_flow_temp_hc1"}),
        (" MaxSetHeatFlowTempHC2: ", 40, 4, "hex", 10, {"translation_key": "max_set_heat_flow_temp_hc2"}),
        (" MinSetHeatFlowTempHC2: ", 44, 4, "hex", 10, {"translation_key": "min_set_heat_flow_temp_hc2"}),
    ],
    "pxx06": [
        ("p21Hyst1: ", 4, 2, "hex", 10, {"translation_key": "hysteresis_1"}),
        (" p22Hyst2: ", 6, 2, "hex", 10, {"translation_key": "hysteresis_2"}),
        (" p23Hyst3: ", 8, 2, "hex", 10, {"translation_key": "hysteresis_3"}),
        (" p24Hyst4: ", 10, 2, "hex", 10, {"translation_key": "hysteresis_4"}),
        (" p25Hyst5: ", 12, 2, "hex", 10, {"translation_key": "hysteresis_5"}),
        (" p26Hyst6: ", 14, 2, "hex", 10, {"translation_key": "hysteresis_6"}),
        (" p27Hyst7: ", 16, 2, "hex", 10, {"translation_key": "hysteresis_7"}),
        (" p28Hyst8: ", 18, 2, "hex", 10, {"translation_key": "hysteresis_8"}),
        (" p29HystAsymmetry: ", 20, 2, "hex", 1, {"translation_key": "hysteresis_asymmetry"}),
        (" p30integralComponent: ", 22, 4, "hex", 1, {"translation_key": "integral_component"}),
        (" p31MaxBoostStages: ", 26, 2, "hex", 1, {"translation_key": "max_boost_stages"}),
        (" MaxHeatFlowTemp: ", 28, 4, "hex", 10, {"translation_key": "max_heat_flow_temp"}),
        (" p49SummerModeTemp: ", 32, 4, "hex", 10, {"translation_key": "summer_mode_temp"}),
        (" p50SummerModeHysteresis: ", 36, 4, "hex", 10, {"translation_key": "summer_mode_hysteresis"}),
        (" p77OutTempFilterTime: ", 40, 4, "hex", 1, {"translation_key": "out_temp_filter_time"}),
        (" p78DualModePoint: ", 44, 4, "hex2int", 10, {**_TEMP, "translation_key": "dual_mode_point"}),
        (" p79BoosterTimeoutHC: ", 48, 2, "hex", 1, {"translation_key": "booster_timeout_hc"}),
    ],
    "pxx07": [
        ("p32HystDHW: ", 4, 2, "hex", 10, {"translation_key": "hysteresis_dhw"}),
        (" p33BoosterTimeoutDHW: ", 6, 2, "hex", 1, {"translation_key": "booster_timeout_dhw"}),
        (" p34TempLimitBoostDHW: ", 8, 4, "hex2int", 10, {**_TEMP, "translation_key": "temp_limit_boost_dhw"}),
        (" p35PasteurisationInterval: ", 12, 2, "hex", 1, {"translation_key": "pasteurization_interval"}),
        (" p36MaxDurationDHWLoad: ", 14, 2, "hex", 1, {"translation_key": "max_duration_dhw_load"}),
        (" pasteurisationTemp: ", 16, 4, "hex", 10, {"translation_key": "pasteurisation_temp"}),
        (" maxBoostStagesDHW: ", 20, 2, "hex", 1, {"translation_key": "max_boost_stages_dhw"}),
        (" p84EnableDHWBuffer: ", 22, 2, "hex", 1, {"translation_key": "enable_dhw_buffer"}),
    ],
    "pxx08": [
        ("p80EnableSolar: ", 4, 2, "hex", 1, {"translation_key": "enable_solar"}),
        (" p81DiffTempSolarLoading: ", 6, 4, "hex", 10, {"translation_key": "diff_temp_solar_loading"}),
        (" p82DelayCompStartSolar: ", 10, 2, "hex", 1, {"translation_key": "delay_comp_start_solar"}),
        (" p84DHWTempSolarMode: ", 12, 4, "hex", 10, {"translation_key": "dhw_temp_solar_mode"}),
        (" HystDiffTempSolar: ", 16, 4, "hex", 10, {"translation_key": "hyst_diff_temp_solar"}),
        (" CollectLimitTempSolar: ", 20, 4, "hex", 10, {"translation_key": "collect_limit_temp_solar"}),
    ],
    "pxx09": [
        ("operatingHours1: ", 4, 4, "hex", 1, {"translation_key": "operating_hours1"}),
        (" operatingHours2: ", 8, 4, "hex", 1, {"translation_key": "operating_hours2"}),
        (" heatingHours: ", 12, 4, "hex", 1, {"translation_key": "heating_hours"}),
        (" DHWhours: ", 16, 4, "hex", 1, {"translation_key": "dhw_hours"}),
        (" coolingHours: ", 20, 4, "hex", 1, {"translation_key": "cooling_hours"}),
    ],
    "pxx0A": [
        ("p54MinPumpCycles: ", 4, 2, "hex", 1, {"translation_key": "min_pump_cycles"}),
        (" p55MaxPumpCycles: ", 6, 4, "hex", 1, {"translation_key": "max_pump_cycles"}),
        (" p56OutTempMaxPumpCycles: ", 10, 4, "hex", 10, {"translation_key": "out_temp_max_pump_cycles"}),
        (" p57OutTempMinPumpCycles: ", 14, 4, "hex", 10, {"translation_key": "out_temp_min_pump_cycles"}),
        (" p58SuppressTempCaptPumpStart: ", 18, 4, "hex", 1, {"translation_key": "suppress_temp_capt_pump_start"}),
    ],
    "pxx0B": [
        ("progHC1StartTime: ", 4, 4, "hex2time", 1, {"translation_key": "prog_hc1_start_time"}),
        (" progHC1EndTime: ", 8, 4, "hex2time", 1, {"translation_key": "prog_hc1_end_time"}),
        (" progHC1Monday: ", 13, 1, "bit0", 1, {"translation_key": "prog_hc1_monday"}),
        (" progHC1Tuesday: ", 13, 1, "bit1", 1, {"translation_key": "prog_hc1_tuesday"}),
        (" progHC1Wednesday: ", 13, 1, "bit2", 1, {"translation_key": "prog_hc1_wednesday"}),
        (" progHC1Thursday: ", 13, 1, "bit3", 1, {"translation_key": "prog_hc1_thursday"}),
        (" progHC1Friday: ", 12, 1, "bit0", 1, {"translation_key": "prog_hc1_friday"}),
        (" progHC1Saturday: ", 12, 1, "bit1", 1, {"translation_key": "prog_hc1_saturday"}),
        (" progHC1Sunday: ", 12, 1, "bit2", 1, {"translation_key": "prog_hc1_sunday"}),
        (" progHC1Enable: ", 14, 2, "hex", 1, {"translation_key": "prog_hc1_enable"}),
        (" progHC2StartTime: ", 16, 4, "hex2time", 1, {"translation_key": "prog_hc2_start_time"}),
        (" progHC2EndTime: ", 20, 4, "hex2time", 1, {"translation_key": "prog_hc2_end_time"}),
        (" progHC2Monday: ", 25, 1, "bit0", 1, {"translation_key": "prog_hc2_monday"}),
        (" progHC2Tuesday: ", 25, 1, "bit1", 1, {"translation_key": "prog_hc2_tuesday"}),
        (" progHC2Wednesday: ", 25, 1, "bit2", 1, {"translation_key": "prog_hc2_wednesday"}),
        (" progHC2Thursday: ", 25, 1, "bit3", 1, {"translation_key": "prog_hc2_thursday"}),
        (" progHC2Friday: ", 24, 1, "bit0", 1, {"translation_key": "prog_hc2_friday"}),
        (" progHC2Saturday: ", 24, 1, "bit1", 1, {"translation_key": "prog_hc2_saturday"}),
        (" progHC2Sunday: ", 24, 1, "bit2", 1, {"translation_key": "prog_hc2_sunday"}),
        (" progHC2Enable: ", 26, 2, "hex", 1, {"translation_key": "prog_hc2_enable"}),
    ],
    "pxx0C": [
        ("progDHWStartTime: ", 4, 4, "hex2time", 1, {"translation_key": "prog_dhw_start_time"}),
        (" progDHWEndTime: ", 8, 4, "hex2time", 1, {"translation_key": "prog_dhw_end_time"}),
        (" progDHWMonday: ", 13, 1, "bit0", 1, {"translation_key": "prog_dhw_monday"}),
        (" progDHWTuesday: ", 13, 1, "bit1", 1, {"translation_key": "prog_dhw_tuesday"}),
        (" progDHWWednesday: ", 13, 1, "bit2", 1, {"translation_key": "prog_dhw_wednesday"}),
        (" progDHWThursday: ", 13, 1, "bit3", 1, {"translation_key": "prog_dhw_thursday"}),
        (" progDHWFriday: ", 12, 1, "bit0", 1, {"translation_key": "prog_dhw_friday"}),
        (" progDHWSaturday: ", 12, 1, "bit1", 1, {"translation_key": "prog_dhw_saturday"}),
        (" progDHWSunday: ", 12, 1, "bit2", 1, {"translation_key": "prog_dhw_sunday"}),
        (" progDHWEnable: ", 14, 2, "hex", 1, {"translation_key": "prog_dhw_enable"}),
    ],
    "pxxD1": [
        ("number_of_faults: ", 4, 2, "hex", 1, {"translation_key": "number_of_faults"}),
        (" fault0CODE: ", 8, 4, "faultmap", 1, {"translation_key": "fault0_code"}),
        (" fault0TIME: ", 12, 4, "hex2time", 1, {"translation_key": "fault0_time"}),
        (" fault0DATE: ", 16, 4, "hexdate", 1, {"translation_key": "fault0_date"}),
        (" fault1CODE: ", 20, 4, "faultmap", 1, {"translation_key": "fault1_code"}),
        (" fault1TIME: ", 24, 4, "hex2time", 1, {"translation_key": "fault1_time"}),
        (" fault1DATE: ", 28, 4, "hexdate", 1, {"translation_key": "fault1_date"}),
        (" fault2CODE: ", 32, 4, "faultmap", 1, {"translation_key": "fault2_code"}),
        (" fault2TIME: ", 36, 4, "hex2time", 1, {"translation_key": "fault2_time"}),
        (" fault2DATE: ", 40, 4, "hexdate", 1, {"translation_key": "fault2_date"}),
        (" fault3CODE: ", 44, 4, "faultmap", 1, {"translation_key": "fault3_code"}),
        (" fault3TIME: ", 48, 4, "hex2time", 1, {"translation_key": "fault3_time"}),
        (" fault3DATE: ", 52, 4, "hexdate", 1, {"translation_key": "fault3_date"}),
    ],
    "pxx0D": [
        ("progFAN1StartTime: ", 4, 4, "hex2time", 1, {"translation_key": "prog_fan1_start_time"}),
        (" progFAN1EndTime: ", 8, 4, "hex2time", 1, {"translation_key": "prog_fan1_end_time"}),
        (" progFAN1Monday: ", 13, 1, "bit0", 1, {"translation_key": "prog_fan1_monday"}),
        (" progFAN1Tuesday: ", 13, 1, "bit1", 1, {"translation_key": "prog_fan1_tuesday"}),
        (" progFAN1Wednesday: ", 13, 1, "bit2", 1, {"translation_key": "prog_fan1_wednesday"}),
        (" progFAN1Thursday: ", 13, 1, "bit3", 1, {"translation_key": "prog_fan1_thursday"}),
        (" progFAN1Friday: ", 12, 1, "bit0", 1, {"translation_key": "prog_fan1_friday"}),
        (" progFAN1Saturday: ", 12, 1, "bit1", 1, {"translation_key": "prog_fan1_saturday"}),
        (" progFAN1Sunday: ", 12, 1, "bit2", 1, {"translation_key": "prog_fan1_sunday"}),
        (" progFAN1Enable: ", 14, 2, "hex", 1, {"translation_key": "prog_fan1_enable"}),
        (" progFAN2StartTime: ", 16, 4, "hex2time", 1, {"translation_key": "prog_fan2_start_time"}),
        (" progFAN2EndTime: ", 20, 4, "hex2time", 1, {"translation_key": "prog_fan2_end_time"}),
        (" progFAN2Monday: ", 25, 1, "bit0", 1, {"translation_key": "prog_fan2_monday"}),
        (" progFAN2Tuesday: ", 25, 1, "bit1", 1, {"translation_key": "prog_fan2_tuesday"}),
        (" progFAN2Wednesday: ", 25, 1, "bit2", 1, {"translation_key": "prog_fan2_wednesday"}),
        (" progFAN2Thursday: ", 25, 1, "bit3", 1, {"translation_key": "prog_fan2_thursday"}),
        (" progFAN2Friday: ", 24, 1, "bit0", 1, {"translation_key": "prog_fan2_friday"}),
        (" progFAN2Saturday: ", 24, 1, "bit1", 1, {"translation_key": "prog_fan2_saturday"}),
        (" progFAN2Sunday: ", 24, 1, "bit2", 1, {"translation_key": "prog_fan2_sunday"}),
        (" progFAN2Enable: ", 26, 2, "hex", 1, {"translation_key": "prog_fan2_enable"}),
    ],
    "pxx0E": [("p59RestartBeforeSetbackEnd: ", 4, 4, "hex", 1, {"translation_key": "restart_before_setback_end"})],
    "pxx0F": [
        ("pA0DurationUntilAbsenceStart: ", 4, 4, "hex", 10, {"translation_key": "duration_until_absence_start"}),
        (" pA0AbsenceDuration: ", 8, 4, "hex", 10, {"translation_key": "absence_duration"}),
        (" pA0EnableAbsenceProg: ", 12, 2, "hex", 1, {"translation_key": "enable_absence_prog"}),
    ],
    "pxx10": [
        ("p70StartDryHeat: ", 4, 2, "hex", 1, {"translation_key": "start_dry_heat"}),
        (" p71BaseTemp: ", 6, 4, "hex", 10, {"translation_key": "base_temp"}),
        (" p72PeakTemp: ", 10, 4, "hex", 10, {"translation_key": "peak_temp"}),
        (" p73TempDuration: ", 14, 4, "hex", 1, {"translation_key": "temp_duration"}),
        (" p74TempIncrease: ", 18, 4, "hex", 10, {"translation_key": "temp_increase"}),
    ],
    "pxx17": [
        ("p01RoomTempDay: ", 4, 4, "hex", 10, {"translation_key": "room_temp_day"}),
        (" p02RoomTempNight: ", 8, 4, "hex", 10, {"translation_key": "room_temp_night"}),
        (" p03RoomTempStandby: ", 12, 4, "hex", 10, {"translation_key": "room_temp_standby"}),
        (" p04DHWsetTempDay: ", 16, 4, "hex", 10, {"translation_key": "dhw_temp_day"}),
        (" p05DHWsetTempNight: ", 20, 4, "hex", 10, {"translation_key": "dhw_temp_night"}),
        (" p06DHWsetTempStandby: ", 24, 4, "hex", 10, {"translation_key": "dhw_temp_standby"}),
        (" p07FanStageDay: ", 28, 2, "hex", 1, {"translation_key": "fan_stage_day"}),
        (" p08FanStageNight: ", 30, 2, "hex", 1, {"translation_key": "fan_stage_night"}),
        (" p09FanStageStandby: ", 32, 2, "hex", 1, {"translation_key": "fan_stage_standby"}),
        (" p10HCTempManual: ", 34, 4, "hex", 10, {"translation_key": "hc_temp_manual"}),
        (" p11DHWsetTempManual: ", 38, 4, "hex", 10, {"translation_key": "dhw_temp_manual"}),
        (" p12FanStageManual: ", 42, 2, "hex", 1, {"translation_key": "fan_stage_manual"}),
    ],
    "pxxE8": [
        (
            "statusAFC: ",
            4,
            4,
            "hex",
            1,
            {"translation_key": "status_afc"},
        ),  # 0=init air flow calibration (16:00) 4=normal fan operation
        (" supplyFanSpeedCAL: ", 8, 4, "hex", 60, {"translation_key": "supply_fan_speed_cal"}),  # calibration speed
        (" exhaustFanSpeedCAL: ", 12, 4, "hex", 60, {"translation_key": "exhaust_fan_speed_cal"}),
        (" supplyFanAirflowCAL: ", 16, 4, "hex", 100, {"translation_key": "supply_fan_airflow_cal"}),  # calibration air flow volume
        (" exhaustFanAirflowCAL: ", 20, 4, "hex", 100, {"translation_key": "exhaust_fan_airflow_cal"}),
        (" supplyFanSpeed: ", 24, 4, "hex", 1, {"translation_key": "supply_fan_speed"}),  # actual fan speed in 1/s
        (" exhaustFanSpeed: ", 28, 4, "hex", 1, {"translation_key": "exhaust_fan_speed"}),
        (
            " supplyFanAirflowSet: ",
            32,
            4,
            "hex",
            1,
            {"translation_key": "supply_fan_airflow_set"},
        ),  # actual air flow volume setting in m3/h
        (" exhaustFanAirflowSet: ", 36, 4, "hex", 1, {"translation_key": "exhaust_fan_airflow_set"}),
        (" supplyFanSpeedTarget: ", 40, 4, "hex", 1, {"translation_key": "supply_fan_speed_target"}),  # target fan speed in %
        (" exhaustFanSpeedTarget: ", 44, 4, "hex", 1, {"translation_key": "exhaust_fan_speed_target"}),
        (" supplyFanSpeed0: ", 48, 4, "hex", 10, {"translation_key": "supply_fan_speed0"}),
        (" exhaustFanSpeed0: ", 52, 4, "hex", 10, {"translation_key": "exhaust_fan_speed0"}),
        (" supplyFanSpeed200: ", 56, 4, "hex", 10, {"translation_key": "supply_fan_speed200"}),
        (" exhaustFanSpeed200: ", 60, 4, "hex", 10, {"translation_key": "exhaust_fan_speed200"}),
        (" airflowTolerance: ", 64, 2, "hex", 1, {"translation_key": "airflow_tolerance"}),
        (" airflowCalibrationInterval: ", 66, 2, "hex", 1, {"translation_key": "airflow_calibration_interval"}),  # calibration interval
        (" timeToCalibration: ", 68, 2, "hex", 1, {"translation_key": "time_to_calibration"}),  # days to next calibration
    ],
    "pxxEE": [
        ("opMode: ", 4, 2, "opmode2", 1, {"translation_key": "op_mode"}),
        (" ProgStateHC: ", 10, 2, "opmodehc", 1, {"translation_key": "prog_state_hc"}),
        (" ProgStateDHW: ", 12, 2, "opmodehc", 1, {"translation_key": "prog_state_dhw"}),
        (" ProgStateFAN: ", 14, 2, "opmodehc", 1, {"translation_key": "prog_state_fan"}),
        (" BaseTimeAP0: ", 16, 8, "hex", 1, {"translation_key": "base_time_ap0"}),
        (" StatusAP0: ", 24, 2, "hex", 1, {"translation_key": "status_ap0"}),
        (" StartTimeAP0: ", 26, 8, "hex", 1, {"translation_key": "start_time_ap0"}),
        (" EndTimeAP0: ", 34, 8, "hex", 1, {"translation_key": "end_time_ap0"}),
    ],
    "pxxF6": [
        ("userSetFanStage: ", 30, 2, "hex", 1, {"translation_key": "user_set_fan_stage"}),
        (" userSetFanRemainingTime: ", 36, 4, "hex", 1, {"translation_key": "user_set_fan_remaining_time"}),
        (" lastErrors: ", 4, 8, "hex2error", 1, {"translation_key": "last_errors"}),
    ],
    "pxxFB": [
        ("outsideTemp: ", 8, 4, "hex2int", 10, {**_TEMP, "translation_key": "outside_temp"}),
        (" flowTemp: ", 12, 4, "hex2int", 10, {**_TEMP, "translation_key": "flow_temp"}),
        (" returnTemp: ", 16, 4, "hex2int", 10, {**_TEMP, "translation_key": "return_temp"}),
        (" hotGasTemp: ", 20, 4, "hex2int", 10, {**_TEMP, "translation_key": "hotgas_temp"}),
        (" dhwTemp: ", 24, 4, "hex2int", 10, {**_TEMP, "icon": "mdi:water-boiler", "translation_key": "dhw_temp"}),
        (" flowTempHC2: ", 28, 4, "hex2int", 10, {**_TEMP, "translation_key": "flow_temp_hc2"}),
        (" evaporatorTemp: ", 36, 4, "hex2int", 10, {**_TEMP, "icon": "mdi:snowflake", "translation_key": "evaporator_temp"}),
        (" condenserTemp: ", 40, 4, "hex2int", 10, {**_TEMP, "icon": "mdi:radiator", "translation_key": "condenser_temp"}),
        (" mixerOpen: ", 47, 1, "bit1", 1, {"icon": "mdi:gate-open", "translation_key": "mixer_open"}),
        (" mixerClosed: ", 47, 1, "bit0", 1, {"icon": "mdi:gate", "translation_key": "mixer_closed"}),
        (" heatPipeValve: ", 45, 1, "bit3", 1, {"icon": "mdi:valve", "translation_key": "heat_pipe_valve"}),
        (" diverterValve: ", 45, 1, "bit2", 1, {"icon": "mdi:valve", "translation_key": "diverter_valve"}),
        (" dhwPump: ", 45, 1, "bit1", 1, {"icon": "mdi:pump", "translation_key": "dhw_pump"}),
        (" heatingCircuitPump: ", 45, 1, "bit0", 1, {"icon": "mdi:pump", "translation_key": "heating_circuit_pump"}),
        # solarPump: nibble 44 is fully claimed by compressor/boosterStage1-3
        # below on firmware 2.06 -- FHEM's own FBglob206 table has the exact
        # same "n.a" placeholder (note: no trailing dot, unlike the "n.a."
        # used elsewhere -- a pre-existing typo in FHEM's own source, kept
        # here for fidelity) here too, with no bit ever assigned. This is
        # matching a known upstream limitation, not a bug in this port --
        # there is no correct bit number to substitute without new
        # hardware reverse-engineering.
        (" solarPump: ", 44, 1, "n.a", 1, {"icon": "mdi:weather-sunny", "translation_key": "solar_pump"}),
        (" compressor: ", 44, 1, "bit0", 1, {"icon": "mdi:engine", "translation_key": "compressor"}),
        (" boosterStage3: ", 44, 1, "bit3", 1, {"translation_key": "booster_stage_3"}),
        (" boosterStage2: ", 44, 1, "bit2", 1, {"translation_key": "booster_stage_2"}),
        (" boosterStage1: ", 44, 1, "bit1", 1, {"translation_key": "booster_stage_1"}),
        (" highPressureSensor: ", 54, 1, "bit3", 1, {"translation_key": "high_pressure_sensor"}),
        (" lowPressureSensor: ", 54, 1, "bit2", 1, {"translation_key": "low_pressure_sensor"}),
        (" evaporatorIceMonitor: ", 55, 1, "bit3", 1, {"translation_key": "evaporator_ice_monitor"}),
        (" signalAnode: ", 54, 1, "bit1", 1, {"translation_key": "signal_anode"}),
        # evuRelease / STB: nibble 48 was repurposed on firmware 2.06 to carry
        # outputVentilatorPower as a 2-nibble value instead of individual
        # flag bits (see below). FHEM's own FBglob206 table marks both as
        # "n.a." for exactly this reason -- matching a known upstream
        # limitation, not a bug in this port.
        (" evuRelease: ", 48, 1, "n.a.", 1, {"translation_key": "evu_release"}),
        (" ovenFireplace: ", 54, 1, "bit0", 1, {"translation_key": "oven_fireplace"}),
        (" STB: ", 48, 1, "n.a.", 1, {"translation_key": "stb"}),
        (" outputVentilatorPower: ", 48, 2, "hex", 1, {**_FAN_POWER, "translation_key": "output_ventilator_power"}),
        (" inputVentilatorPower: ", 50, 2, "hex", 1, {**_FAN_POWER, "translation_key": "input_ventilator_power"}),
        (" mainVentilatorPower: ", 52, 2, "hex", 255 / 100, {**_FAN_POWER, "translation_key": "main_ventilator_power"}),
        (" outputVentilatorSpeed: ", 56, 2, "hex", 1, {**_SPEED, "translation_key": "output_ventilator_speed"}),
        (" inputVentilatorSpeed: ", 58, 2, "hex", 1, {**_SPEED, "translation_key": "input_ventilator_speed"}),
        (" mainVentilatorSpeed: ", 60, 2, "hex", 1, {**_SPEED, "translation_key": "main_ventilator_speed"}),
        (" outsideTempFiltered: ", 64, 4, "hex2int", 10, {**_TEMP, "translation_key": "outside_temp_filtered"}),
        (" relHumidity: ", 70, 4, "n.a.", 1, {"icon": "mdi:water-percent", "translation_key": "rel_humidity"}),
        (" dewPoint: ", 5, 4, "n.a.", 1, {"icon": "mdi:weather-fog", "translation_key": "dew_point"}),
        (" P_Nd: ", 5, 4, "n.a.", 1, {"translation_key": "pressure_nd"}),
        (" P_Hd: ", 5, 4, "n.a.", 1, {"translation_key": "pressure_hd"}),
        (" actualPower_Qc: ", 5, 8, "n.a.", 1, {"translation_key": "actual_power_qc"}),
        (" actualPower_Pel: ", 5, 8, "n.a.", 1, {"translation_key": "actual_power_pel"}),
        (" collectorTemp: ", 4, 4, "hex2int", 10, {**_TEMP, "icon": "mdi:solar-power", "translation_key": "collector_temp"}),
        (" insideTemp: ", 32, 4, "hex2int", 10, {**_TEMP, "icon": "mdi:home-thermometer", "translation_key": "inside_temp"}),
    ],
    "pxxFC": [
        ("Weekday: ", 7, 1, "weekday", 1, {"translation_key": "weekday"}),
        (" pClockHour: ", 8, 2, "hex", 1, {"translation_key": "clock_hour"}),
        (" pClockMinutes: ", 10, 2, "hex", 1, {"translation_key": "clock_minutes"}),
        (" Sec: ", 12, 2, "hex", 1, {"translation_key": "clock_sec"}),
        (" pClockYear: ", 14, 2, "hex", 1, {"translation_key": "clock_year"}),
        (" pClockMonth: ", 18, 2, "hex", 1, {"translation_key": "clock_month"}),
        (" pClockDay: ", 20, 2, "hex", 1, {"translation_key": "clock_day"}),
    ],
}
