"""This module defines the WRITE_MAP dictionary for firmware version "206" used in the THZ component.

WRITE_MAP contains configuration parameters for various device settings, such as temperature, fan stages, hysteresis, pump cycles, and scheduling programs. Each parameter is represented as a dictionary with metadata including parent group, minimum and maximum values, unit, step, type, device class, icon, and decode type.

The map is used to validate and describe writable registers for the device, supporting features like heating, cooling, fan control, DHW (domestic hot water), solar, and scheduling.

Example parameter entry:

This structure enables dynamic configuration and validation of device settings in Home Assistant integrations.
"""

WRITE_MAP = {
    "firmware": "206",
    "p01RoomTempDay": {
        "parent": "p01-p12",
        "min": "10",
        "max": "30",
        "unit": " °C",
        "step": "",
        "type": "number",
        "device_class": "",
        "icon": "mdi:swap-horizontal",
        "decode_type": "pClean",
    },
    "p02RoomTempNight": {
        "parent": "p01-p12",
        "min": "10",
        "max": "30",
        "unit": " °C",
        "step": "",
        "type": "number",
        "device_class": "",
        "icon": "mdi:swap-horizontal",
        "decode_type": "pClean",
    },
    "p03RoomTempStandby": {
        "parent": "p01-p12",
        "min": "10",
        "max": "30",
        "unit": " °C",
        "step": "",
        "type": "number",
        "device_class": "",
        "icon": "mdi:swap-horizontal",
        "decode_type": "pClean",
    },
    "p04DHWsetTempDay": {
        "parent": "p01-p12",
        "min": "10",
        "max": "55",
        "unit": " °C",
        "step": "",
        "type": "number",
        "device_class": "",
        "icon": "mdi:swap-horizontal",
        "decode_type": "pClean",
    },
    "p05DHWsetTempNight": {
        "parent": "p01-p12",
        "min": "10",
        "max": "55",
        "unit": " °C",
        "step": "",
        "type": "number",
        "device_class": "",
        "icon": "mdi:swap-horizontal",
        "decode_type": "pClean",
    },
    "p06DHWsetTempStandby": {
        "parent": "p01-p12",
        "min": "10",
        "max": "55",
        "unit": " °C",
        "step": "",
        "type": "number",
        "device_class": "",
        "icon": "mdi:swap-horizontal",
        "decode_type": "pClean",
    },
    "p07FanStageDay": {
        "parent": "p01-p12",
        "min": "0",
        "max": "3",
        "unit": "",
        "step": "",
        "type": "number",
        "device_class": "",
        "icon": "mdi:swap-horizontal",
        "decode_type": "pClean",
    },
    "p08FanStageNight": {
        "parent": "p01-p12",
        "min": "0",
        "max": "3",
        "unit": "",
        "step": "",
        "type": "number",
        "device_class": "",
        "icon": "mdi:swap-horizontal",
        "decode_type": "pClean",
    },
    "p09FanStageStandby": {
        "parent": "p01-p12",
        "min": "0",
        "max": "3",
        "unit": "",
        "step": "",
        "type": "number",
        "device_class": "",
        "icon": "mdi:swap-horizontal",
        "decode_type": "pClean",
    },
    "p10HCTempManual": {
        "parent": "p01-p12",
        "min": "10",
        "max": "65",
        "unit": " °C",
        "step": "",
        "type": "number",
        "device_class": "",
        "icon": "mdi:swap-horizontal",
        "decode_type": "pClean",
    },
    "p11DHWsetTempManual": {
        "parent": "p01-p12",
        "min": "10",
        "max": "65",
        "unit": " °C",
        "step": "",
        "type": "number",
        "device_class": "",
        "icon": "mdi:swap-horizontal",
        "decode_type": "pClean",
    },
    "p12FanStageManual": {
        "parent": "p01-p12",
        "min": "0",
        "max": "3",
        "unit": "",
        "step": "",
        "type": "number",
        "device_class": "",
        "icon": "mdi:swap-horizontal",
        "decode_type": "pClean",
    },
    "p13GradientHC1": {
        "parent": "pHeat1",
        "min": "0",
        "max": "5",
        "unit": "",
        "step": "",
        "type": "number",
        "device_class": "",
        "icon": "mdi:swap-horizontal",
        "decode_type": "pClean",
    },
    "p14LowEndHC1": {
        "parent": "pHeat1",
        "min": "0",
        "max": "20",
        "unit": " K",
        "step": "",
        "type": "number",
        "device_class": "",
        "icon": "mdi:swap-horizontal",
        "decode_type": "pClean",
    },
    "p15RoomInfluenceHC1": {
        "parent": "pHeat1",
        "min": "0",
        "max": "10",
        "unit": "",
        "step": "",
        "type": "number",
        "device_class": "",
        "icon": "mdi:swap-horizontal",
        "decode_type": "pClean",
    },
    "p16GradientHC2": {
        "parent": "pHeat1",
        "min": "0",
        "max": "5",
        "unit": "",
        "step": "",
        "type": "number",
        "device_class": "",
        "icon": "mdi:swap-horizontal",
        "decode_type": "pClean",
    },
    "p17LowEndHC2": {
        "parent": "pHeat1",
        "min": "0",
        "max": "10",
        "unit": " K",
        "step": "",
        "type": "number",
        "device_class": "",
        "icon": "mdi:swap-horizontal",
        "decode_type": "pClean",
    },
    "p18RoomInfluenceHC2": {
        "parent": "pHeat1",
        "min": "0",
        "max": "10",
        "unit": "",
        "step": "",
        "type": "number",
        "device_class": "",
        "icon": "mdi:swap-horizontal",
        "decode_type": "pClean",
    },
    "p19FlowProportionHC1": {
        "parent": "pHeat1",
        "min": "0",
        "max": "100",
        "unit": " %",
        "step": "",
        "type": "number",
        "device_class": "",
        "icon": "mdi:swap-horizontal",
        "decode_type": "pClean",
    },
    "p20FlowProportionHC2": {
        "parent": "pHeat1",
        "min": "0",
        "max": "100",
        "unit": " %",
        "step": "",
        "type": "number",
        "device_class": "",
        "icon": "mdi:swap-horizontal",
        "decode_type": "pClean",
    },
    "p21Hyst1": {
        "parent": "pHeat2",
        "min": "0",
        "max": "10",
        "unit": " K",
        "step": "",
        "type": "number",
        "device_class": "",
        "icon": "mdi:swap-horizontal",
        "decode_type": "pClean",
    },
    "p22Hyst2": {
        "parent": "pHeat2",
        "min": "0",
        "max": "10",
        "unit": " K",
        "step": "",
        "type": "number",
        "device_class": "",
        "icon": "mdi:swap-horizontal",
        "decode_type": "pClean",
    },
    "p23Hyst3": {
        "parent": "pHeat2",
        "min": "0",
        "max": "5",
        "unit": " K",
        "step": "",
        "type": "number",
        "device_class": "",
        "icon": "mdi:swap-horizontal",
        "decode_type": "pClean",
    },
    "p24Hyst4": {
        "parent": "pHeat2",
        "min": "0",
        "max": "5",
        "unit": " K",
        "step": "",
        "type": "number",
        "device_class": "",
        "icon": "mdi:swap-horizontal",
        "decode_type": "pClean",
    },
    "p25Hyst5": {
        "parent": "pHeat2",
        "min": "0",
        "max": "5",
        "unit": " K",
        "step": "",
        "type": "number",
        "device_class": "",
        "icon": "mdi:swap-horizontal",
        "decode_type": "pClean",
    },
    "p29HystAsymmetry": {
        "parent": "pHeat2",
        "min": "1",
        "max": "5",
        "unit": "",
        "step": "",
        "type": "number",
        "device_class": "",
        "icon": "mdi:swap-horizontal",
        "decode_type": "pClean",
    },
    "p30integralComponent": {
        "parent": "pHeat2",
        "min": "10",
        "max": "999",
        "unit": " Kmin",
        "step": "",
        "type": "number",
        "device_class": "",
        "icon": "mdi:swap-horizontal",
        "decode_type": "pClean",
    },
    "p32HystDHW": {
        "parent": "pDHW",
        "min": "2",
        "max": "10",
        "unit": " K",
        "step": "",
        "type": "number",
        "device_class": "",
        "icon": "mdi:swap-horizontal",
        "decode_type": "pClean",
    },
    "p33BoosterTimeoutDHW": {
        "parent": "pDHW",
        "min": "0",
        "max": "240",
        "unit": " min",
        "step": "",
        "type": "number",
        "device_class": "",
        "icon": "mdi:swap-horizontal",
        "decode_type": "pClean",
    },
    "p34TempLimitBoostDHW": {
        "parent": "pDHW",
        "min": "-10",
        "max": "10",
        "unit": " °C",
        "step": "",
        "type": "number",
        "device_class": "",
        "icon": "mdi:swap-horizontal",
        "decode_type": "pClean",
    },
    "p35PasteurisationInterval": {
        "parent": "pDHW",
        "min": "3",
        "max": "30",
        "unit": " Days",
        "step": "",
        "type": "number",
        "device_class": "",
        "icon": "mdi:swap-horizontal",
        "decode_type": "pClean",
    },
    "p36MaxDurationDHWLoad": {
        "parent": "pDHW",
        "min": "6",
        "max": "12",
        "unit": " h",
        "step": "",
        "type": "number",
        "device_class": "",
        "icon": "mdi:swap-horizontal",
        "decode_type": "pClean",
    },
    "p37Fanstage1AirflowInlet": {
        "parent": "pFan",
        "min": "60",
        "max": "250",
        "unit": " m3/h",
        "step": "",
        "type": "number",
        "device_class": "",
        "icon": "mdi:swap-horizontal",
        "decode_type": "pClean",
    },
    "p38Fanstage2AirflowInlet": {
        "parent": "pFan",
        "min": "60",
        "max": "250",
        "unit": " m3/h",
        "step": "",
        "type": "number",
        "device_class": "",
        "icon": "mdi:swap-horizontal",
        "decode_type": "pClean",
    },
    "p39Fanstage3AirflowInlet": {
        "parent": "pFan",
        "min": "60",
        "max": "250",
        "unit": " m3/h",
        "step": "",
        "type": "number",
        "device_class": "",
        "icon": "mdi:swap-horizontal",
        "decode_type": "pClean",
    },
    "p40Fanstage1AirflowOutlet": {
        "parent": "pFan",
        "min": "60",
        "max": "250",
        "unit": " m3/h",
        "step": "",
        "type": "number",
        "device_class": "",
        "icon": "mdi:swap-horizontal",
        "decode_type": "pClean",
    },
    "p41Fanstage2AirflowOutlet": {
        "parent": "pFan",
        "min": "60",
        "max": "250",
        "unit": " m3/h",
        "step": "",
        "type": "number",
        "device_class": "",
        "icon": "mdi:swap-horizontal",
        "decode_type": "pClean",
    },
    "p42Fanstage3AirflowOutlet": {
        "parent": "pFan",
        "min": "60",
        "max": "250",
        "unit": " m3/h",
        "step": "",
        "type": "number",
        "device_class": "",
        "icon": "mdi:swap-horizontal",
        "decode_type": "pClean",
    },
    "p43UnschedVent3": {
        "parent": "pFan",
        "min": "0",
        "max": "1000",
        "unit": " min",
        "step": "",
        "type": "number",
        "device_class": "",
        "icon": "mdi:swap-horizontal",
        "decode_type": "pClean",
    },
    "p44UnschedVent2": {
        "parent": "pFan",
        "min": "0",
        "max": "1000",
        "unit": " min",
        "step": "",
        "type": "number",
        "device_class": "",
        "icon": "mdi:swap-horizontal",
        "decode_type": "pClean",
    },
    "p45UnschedVent1": {
        "parent": "pFan",
        "min": "0",
        "max": "1000",
        "unit": " min",
        "step": "",
        "type": "number",
        "device_class": "",
        "icon": "mdi:swap-horizontal",
        "decode_type": "pClean",
    },
    "p46UnschedVent0": {
        "parent": "pFan",
        "min": "0",
        "max": "1000",
        "unit": " min",
        "step": "",
        "type": "number",
        "device_class": "",
        "icon": "mdi:swap-horizontal",
        "decode_type": "pClean",
    },
    "p47CompressorRestartDelay": {
        "parent": "pDefrostEva",
        "min": "0",
        "max": "20",
        "unit": " min",
        "step": "",
        "type": "number",
        "device_class": "",
        "icon": "mdi:swap-horizontal",
        "decode_type": "pClean",
    },
    "p48MainFanSpeed": {
        "parent": "pDefrostEva",
        "min": "0",
        "max": "100",
        "unit": " %",
        "step": "",
        "type": "number",
        "device_class": "",
        "icon": "mdi:swap-horizontal",
        "decode_type": "pClean",
    },
    "p49SummerModeTemp": {
        "parent": "pHeat2",
        "min": "10",
        "max": "24",
        "unit": " °C",
        "step": "",
        "type": "number",
        "device_class": "",
        "icon": "mdi:swap-horizontal",
        "decode_type": "pClean",
    },
    "p50SummerModeHysteresis": {
        "parent": "pHeat2",
        "min": "1",
        "max": "5",
        "unit": " K",
        "step": "",
        "type": "number",
        "device_class": "",
        "icon": "mdi:swap-horizontal",
        "decode_type": "pClean",
    },
    "p54MinPumpCycles": {
        "parent": "pCircPump",
        "min": "1",
        "max": "24",
        "unit": " /Day",
        "step": "",
        "type": "number",
        "device_class": "",
        "icon": "mdi:swap-horizontal",
        "decode_type": "pClean",
    },
    "p55MaxPumpCycles": {
        "parent": "pCircPump",
        "min": "25",
        "max": "288",
        "unit": " /Day",
        "step": "",
        "type": "number",
        "device_class": "",
        "icon": "mdi:swap-horizontal",
        "decode_type": "pClean",
    },
    "p56OutTempMaxPumpCycles": {
        "parent": "pCircPump",
        "min": "0",
        "max": "20",
        "unit": " °C",
        "step": "",
        "type": "number",
        "device_class": "",
        "icon": "mdi:swap-horizontal",
        "decode_type": "pClean",
    },
    "p57OutTempMinPumpCycles": {
        "parent": "pCircPump",
        "min": "0",
        "max": "25",
        "unit": " °C",
        "step": "",
        "type": "number",
        "device_class": "",
        "icon": "mdi:swap-horizontal",
        "decode_type": "pClean",
    },
    "p58SuppressTempCaptPumpStart": {
        "parent": "pCircPump",
        "min": "0",
        "max": "120",
        "unit": " s",
        "step": "",
        "type": "number",
        "device_class": "",
        "icon": "mdi:swap-horizontal",
        "decode_type": "pClean",
    },
    "p75PassiveCooling": {
        "parent": "pFan",
        "min": "0",
        "max": "1",
        "unit": "",
        "step": "",
        "type": "number",
        "device_class": "",
        "icon": "mdi:swap-horizontal",
        "decode_type": "pClean",
    },
    "p77OutTempFilterTime": {
        "parent": "pHeat2",
        "min": "0",
        "max": "24",
        "unit": " h",
        "step": "",
        "type": "number",
        "device_class": "",
        "icon": "mdi:swap-horizontal",
        "decode_type": "pClean",
    },
    "p78DualModePoint": {
        "parent": "pHeat2",
        "min": "-10",
        "max": "20",
        "unit": " °C",
        "step": "",
        "type": "number",
        "device_class": "",
        "icon": "mdi:swap-horizontal",
        "decode_type": "pClean",
    },
    "p79BoosterTimeoutHC": {
        "parent": "pHeat2",
        "min": "0",
        "max": "60",
        "unit": " min",
        "step": "",
        "type": "number",
        "device_class": "",
        "icon": "mdi:swap-horizontal",
        "decode_type": "pClean",
    },
    "p80EnableSolar": {
        "parent": "pSolar",
        "min": "0",
        "max": "1",
        "unit": "",
        "step": "",
        "type": "number",
        "device_class": "",
        "icon": "mdi:swap-horizontal",
        "decode_type": "pClean",
    },
    "pClockDay": {
        "parent": "sTimedate",
        "min": "1",
        "max": "31",
        "unit": "",
        "step": "",
        "type": "number",
        "device_class": "",
        "icon": "mdi:swap-horizontal",
        "decode_type": "pClean",
    },
    "pClockMonth": {
        "parent": "sTimedate",
        "min": "1",
        "max": "12",
        "unit": "",
        "step": "",
        "type": "number",
        "device_class": "",
        "icon": "mdi:swap-horizontal",
        "decode_type": "pClean",
    },
    "pClockYear": {
        "parent": "sTimedate",
        "min": "12",
        "max": "20",
        "unit": "",
        "step": "",
        "type": "number",
        "device_class": "",
        "icon": "mdi:swap-horizontal",
        "decode_type": "pClean",
    },
    "pClockHour": {
        "parent": "sTimedate",
        "min": "0",
        "max": "23",
        "unit": "",
        "step": "",
        "type": "number",
        "device_class": "",
        "icon": "mdi:swap-horizontal",
        "decode_type": "pClean",
    },
    "pClockMinutes": {
        "parent": "sTimedate",
        "min": "0",
        "max": "59",
        "unit": "",
        "step": "",
        "type": "number",
        "device_class": "",
        "icon": "mdi:swap-horizontal",
        "decode_type": "pClean",
    },
    "progDHWStartTime": {
        "parent": "pDHWProg",
        "min": "00:00",
        "max": "23:59",
        "unit": "",
        "step": "",
        "type": "ptime",
        "device_class": "",
        "icon": "mdi:swap-horizontal",
        "decode_type": "pClean",
    },
    "progDHWEndTime": {
        "parent": "pDHWProg",
        "min": "00:00",
        "max": "23:59",
        "unit": "",
        "step": "",
        "type": "ptime",
        "device_class": "",
        "icon": "mdi:swap-horizontal",
        "decode_type": "pClean",
    },
    "progDHWEnable": {
        "parent": "pDHWProg",
        "min": "0",
        "max": "1",
        "unit": "",
        "step": "",
        "type": "number",
        "device_class": "",
        "icon": "mdi:swap-horizontal",
        "decode_type": "pClean",
    },
    "progDHWMonday": {
        "parent": "pDHWProg",
        "min": "0",
        "max": "1",
        "unit": "",
        "step": "",
        "type": "number",
        "device_class": "",
        "icon": "mdi:swap-horizontal",
        "decode_type": "pClean",
    },
    "progDHWTuesday": {
        "parent": "pDHWProg",
        "min": "0",
        "max": "1",
        "unit": "",
        "step": "",
        "type": "number",
        "device_class": "",
        "icon": "mdi:swap-horizontal",
        "decode_type": "pClean",
    },
    "progDHWWednesday": {
        "parent": "pDHWProg",
        "min": "0",
        "max": "1",
        "unit": "",
        "step": "",
        "type": "number",
        "device_class": "",
        "icon": "mdi:swap-horizontal",
        "decode_type": "pClean",
    },
    "progDHWThursday": {
        "parent": "pDHWProg",
        "min": "0",
        "max": "1",
        "unit": "",
        "step": "",
        "type": "number",
        "device_class": "",
        "icon": "mdi:swap-horizontal",
        "decode_type": "pClean",
    },
    "progDHWFriday": {
        "parent": "pDHWProg",
        "min": "0",
        "max": "1",
        "unit": "",
        "step": "",
        "type": "number",
        "device_class": "",
        "icon": "mdi:swap-horizontal",
        "decode_type": "pClean",
    },
    "progDHWSaturday": {
        "parent": "pDHWProg",
        "min": "0",
        "max": "1",
        "unit": "",
        "step": "",
        "type": "number",
        "device_class": "",
        "icon": "mdi:swap-horizontal",
        "decode_type": "pClean",
    },
    "progDHWSunday": {
        "parent": "pDHWProg",
        "min": "0",
        "max": "1",
        "unit": "",
        "step": "",
        "type": "number",
        "device_class": "",
        "icon": "mdi:swap-horizontal",
        "decode_type": "pClean",
    },
    "progHC1StartTime": {
        "parent": "pHeatProg",
        "min": "00:00",
        "max": "23:59",
        "unit": "",
        "step": "",
        "type": "ptime",
        "device_class": "",
        "icon": "mdi:swap-horizontal",
        "decode_type": "pClean",
    },
    "progHC1EndTime": {
        "parent": "pHeatProg",
        "min": "00:00",
        "max": "23:59",
        "unit": "",
        "step": "",
        "type": "ptime",
        "device_class": "",
        "icon": "mdi:swap-horizontal",
        "decode_type": "pClean",
    },
    "progHC1Enable": {
        "parent": "pHeatProg",
        "min": "0",
        "max": "1",
        "unit": "",
        "step": "",
        "type": "number",
        "device_class": "",
        "icon": "mdi:swap-horizontal",
        "decode_type": "pClean",
    },
    "progHC1Monday": {
        "parent": "pHeatProg",
        "min": "0",
        "max": "1",
        "unit": "",
        "step": "",
        "type": "number",
        "device_class": "",
        "icon": "mdi:swap-horizontal",
        "decode_type": "pClean",
    },
    "progHC1Tuesday": {
        "parent": "pHeatProg",
        "min": "0",
        "max": "1",
        "unit": "",
        "step": "",
        "type": "number",
        "device_class": "",
        "icon": "mdi:swap-horizontal",
        "decode_type": "pClean",
    },
    "progHC1Wednesday": {
        "parent": "pHeatProg",
        "min": "0",
        "max": "1",
        "unit": "",
        "step": "",
        "type": "number",
        "device_class": "",
        "icon": "mdi:swap-horizontal",
        "decode_type": "pClean",
    },
    "progHC1Thursday": {
        "parent": "pHeatProg",
        "min": "0",
        "max": "1",
        "unit": "",
        "step": "",
        "type": "number",
        "device_class": "",
        "icon": "mdi:swap-horizontal",
        "decode_type": "pClean",
    },
    "progHC1Friday": {
        "parent": "pHeatProg",
        "min": "0",
        "max": "1",
        "unit": "",
        "step": "",
        "type": "number",
        "device_class": "",
        "icon": "mdi:swap-horizontal",
        "decode_type": "pClean",
    },
    "progHC1Saturday": {
        "parent": "pHeatProg",
        "min": "0",
        "max": "1",
        "unit": "",
        "step": "",
        "type": "number",
        "device_class": "",
        "icon": "mdi:swap-horizontal",
        "decode_type": "pClean",
    },
    "progHC1Sunday": {
        "parent": "pHeatProg",
        "min": "0",
        "max": "1",
        "unit": "",
        "step": "",
        "type": "number",
        "device_class": "",
        "icon": "mdi:swap-horizontal",
        "decode_type": "pClean",
    },
    "progHC2StartTime": {
        "parent": "pHeatProg",
        "min": "00:00",
        "max": "23:59",
        "unit": "",
        "step": "",
        "type": "ptime",
        "device_class": "",
        "icon": "mdi:swap-horizontal",
        "decode_type": "pClean",
    },
    "progHC2EndTime": {
        "parent": "pHeatProg",
        "min": "00:00",
        "max": "23:59",
        "unit": "",
        "step": "",
        "type": "ptime",
        "device_class": "",
        "icon": "mdi:swap-horizontal",
        "decode_type": "pClean",
    },
    "progHC2Enable": {
        "parent": "pHeatProg",
        "min": "0",
        "max": "1",
        "unit": "",
        "step": "",
        "type": "number",
        "device_class": "",
        "icon": "mdi:swap-horizontal",
        "decode_type": "pClean",
    },
    "progHC2Monday": {
        "parent": "pHeatProg",
        "min": "0",
        "max": "1",
        "unit": "",
        "step": "",
        "type": "number",
        "device_class": "",
        "icon": "mdi:swap-horizontal",
        "decode_type": "pClean",
    },
    "progHC2Tuesday": {
        "parent": "pHeatProg",
        "min": "0",
        "max": "1",
        "unit": "",
        "step": "",
        "type": "number",
        "device_class": "",
        "icon": "mdi:swap-horizontal",
        "decode_type": "pClean",
    },
    "progHC2Wednesday": {
        "parent": "pHeatProg",
        "min": "0",
        "max": "1",
        "unit": "",
        "step": "",
        "type": "number",
        "device_class": "",
        "icon": "mdi:swap-horizontal",
        "decode_type": "pClean",
    },
    "progHC2Thursday": {
        "parent": "pHeatProg",
        "min": "0",
        "max": "1",
        "unit": "",
        "step": "",
        "type": "number",
        "device_class": "",
        "icon": "mdi:swap-horizontal",
        "decode_type": "pClean",
    },
    "progHC2Friday": {
        "parent": "pHeatProg",
        "min": "0",
        "max": "1",
        "unit": "",
        "step": "",
        "type": "number",
        "device_class": "",
        "icon": "mdi:swap-horizontal",
        "decode_type": "pClean",
    },
    "progHC2Saturday": {
        "parent": "pHeatProg",
        "min": "0",
        "max": "1",
        "unit": "",
        "step": "",
        "type": "number",
        "device_class": "",
        "icon": "mdi:swap-horizontal",
        "decode_type": "pClean",
    },
    "progHC2Sunday": {
        "parent": "pHeatProg",
        "min": "0",
        "max": "1",
        "unit": "",
        "step": "",
        "type": "number",
        "device_class": "",
        "icon": "mdi:swap-horizontal",
        "decode_type": "pClean",
    },
    "progFAN1StartTime": {
        "parent": "pFanProg",
        "min": "00:00",
        "max": "23:59",
        "unit": "",
        "step": "",
        "type": "ptime",
        "device_class": "",
        "icon": "mdi:swap-horizontal",
        "decode_type": "pClean",
    },
    "progFAN1EndTime": {
        "parent": "pFanProg",
        "min": "00:00",
        "max": "23:59",
        "unit": "",
        "step": "",
        "type": "ptime",
        "device_class": "",
        "icon": "mdi:swap-horizontal",
        "decode_type": "pClean",
    },
    "progFAN1Enable": {
        "parent": "pFanProg",
        "min": "0",
        "max": "1",
        "unit": "",
        "step": "",
        "type": "number",
        "device_class": "",
        "icon": "mdi:swap-horizontal",
        "decode_type": "pClean",
    },
    "progFAN1Monday": {
        "parent": "pFanProg",
        "min": "0",
        "max": "1",
        "unit": "",
        "step": "",
        "type": "number",
        "device_class": "",
        "icon": "mdi:swap-horizontal",
        "decode_type": "pClean",
    },
    "progFAN1Tuesday": {
        "parent": "pFanProg",
        "min": "0",
        "max": "1",
        "unit": "",
        "step": "",
        "type": "number",
        "device_class": "",
        "icon": "mdi:swap-horizontal",
        "decode_type": "pClean",
    },
    "progFAN1Wednesday": {
        "parent": "pFanProg",
        "min": "0",
        "max": "1",
        "unit": "",
        "step": "",
        "type": "number",
        "device_class": "",
        "icon": "mdi:swap-horizontal",
        "decode_type": "pClean",
    },
    "progFAN1Thursday": {
        "parent": "pFanProg",
        "min": "0",
        "max": "1",
        "unit": "",
        "step": "",
        "type": "number",
        "device_class": "",
        "icon": "mdi:swap-horizontal",
        "decode_type": "pClean",
    },
    "progFAN1Friday": {
        "parent": "pFanProg",
        "min": "0",
        "max": "1",
        "unit": "",
        "step": "",
        "type": "number",
        "device_class": "",
        "icon": "mdi:swap-horizontal",
        "decode_type": "pClean",
    },
    "progFAN1Saturday": {
        "parent": "pFanProg",
        "min": "0",
        "max": "1",
        "unit": "",
        "step": "",
        "type": "number",
        "device_class": "",
        "icon": "mdi:swap-horizontal",
        "decode_type": "pClean",
    },
    "progFAN1Sunday": {
        "parent": "pFanProg",
        "min": "0",
        "max": "1",
        "unit": "",
        "step": "",
        "type": "number",
        "device_class": "",
        "icon": "mdi:swap-horizontal",
        "decode_type": "pClean",
    },
    "progFAN2StartTime": {
        "parent": "pFanProg",
        "min": "00:00",
        "max": "23:59",
        "unit": "",
        "step": "",
        "type": "ptime",
        "device_class": "",
        "icon": "mdi:swap-horizontal",
        "decode_type": "pClean",
    },
    "progFAN2EndTime": {
        "parent": "pFanProg",
        "min": "00:00",
        "max": "23:59",
        "unit": "",
        "step": "",
        "type": "ptime",
        "device_class": "",
        "icon": "mdi:swap-horizontal",
        "decode_type": "pClean",
    },
    "progFAN2Enable": {
        "parent": "pFanProg",
        "min": "0",
        "max": "1",
        "unit": "",
        "step": "",
        "type": "number",
        "device_class": "",
        "icon": "mdi:swap-horizontal",
        "decode_type": "pClean",
    },
    "progFAN2Monday": {
        "parent": "pFanProg",
        "min": "0",
        "max": "1",
        "unit": "",
        "step": "",
        "type": "number",
        "device_class": "",
        "icon": "mdi:swap-horizontal",
        "decode_type": "pClean",
    },
    "progFAN2Tuesday": {
        "parent": "pFanProg",
        "min": "0",
        "max": "1",
        "unit": "",
        "step": "",
        "type": "number",
        "device_class": "",
        "icon": "mdi:swap-horizontal",
        "decode_type": "pClean",
    },
    "progFAN2Wednesday": {
        "parent": "pFanProg",
        "min": "0",
        "max": "1",
        "unit": "",
        "step": "",
        "type": "number",
        "device_class": "",
        "icon": "mdi:swap-horizontal",
        "decode_type": "pClean",
    },
    "progFAN2Thursday": {
        "parent": "pFanProg",
        "min": "0",
        "max": "1",
        "unit": "",
        "step": "",
        "type": "number",
        "device_class": "",
        "icon": "mdi:swap-horizontal",
        "decode_type": "pClean",
    },
    "progFAN2Friday": {
        "parent": "pFanProg",
        "min": "0",
        "max": "1",
        "unit": "",
        "step": "",
        "type": "number",
        "device_class": "",
        "icon": "mdi:swap-horizontal",
        "decode_type": "pClean",
    },
    "progFAN2Saturday": {
        "parent": "pFanProg",
        "min": "0",
        "max": "1",
        "unit": "",
        "step": "",
        "type": "number",
        "device_class": "",
        "icon": "mdi:swap-horizontal",
        "decode_type": "pClean",
    },
    "progFAN2Sunday": {
        "parent": "pFanProg",
        "min": "0",
        "max": "1",
        "unit": "",
        "step": "",
        "type": "number",
        "device_class": "",
        "icon": "mdi:swap-horizontal",
        "decode_type": "pClean",
    },
}
