"""Module: /Home Assistant/custom_components/thz/register_maps/write_map_439_539.py.

Module-level constant:
    WRITE_MAP (dict): Mapping of parameter identifiers to metadata required to
    construct write commands for the THZ device/register map (addresses 0x439-0x539).
Each entry in WRITE_MAP is keyed by a string parameter identifier and the value
is a dictionary with the following fields:
    - command (str): Hex string identifying the target command/register (e.g. "0A0112").
    - min (str|number): Minimum allowed value for the parameter (empty string if not applicable).
    - max (str|number): Maximum allowed value for the parameter (empty string if not applicable).
    - unit (str): Human-readable unit (may include a leading space, e.g. " °C", " %").
    - step (str|float|int): Minimum increment/step for the parameter.
    - type (str): Data entry widget/type hint (e.g. "number", "select", "time").
    - device_class (str): Home Assistant device_class hint (may be empty).
    - icon (str): Icon identifier for UI representation (may be empty).
    - decode_type (str): Internal encoding/decoding hint used by the integration to
      format or parse payloads when writing or reading. Examples observed in this map:
        - "*temp" (e.g. "5temp", "4temp"): temperature-like values, usually encoded
          with a fractional resolution (commonly tenths) — validate against min/max
          and scale appropriately before packing.
        - "opmode" (e.g. "2opmode"): enumerated operating modes (select list).
        - "gradient" (e.g. "6gradient"): slope/gradient values, typically float.
        - "*clean" (e.g. "0clean", "1clean"): integer/clean numeric values (no fractional encoding).
        - "time", "7prog", "8party", "9holy": clock/time or program-slot encodings that
          require special formatting (HH:MM or program-specific packing).
      Note: decode_type values are integration-specific hints — consult the integration's
      encoder/decoder functions to see exact packing rules.
Usage notes (high-level):
    - To write a value:
        1. Lookup the metadata: meta = WRITE_MAP[param_id]
        2. Validate the value against meta["min"]/meta["max"] (if provided).
        3. Apply scaling/formatting according to meta["decode_type"] (e.g. multiply
           temperatures by 10 for one-decimal fixed-point encoding).
        4. Encode the formatted value into the payload expected by the device and
           append/associate with meta["command"] when sending.
    - For UI generation, the fields "type", "unit", "step", "device_class", and "icon"
      provide hints for building controls (numeric sliders, time pickers, selects, etc).
This mapping is intended to be authoritative for the specified register range and is
used by the custom component to provide both UI controls and the correct wire-format
when issuing write commands to the THZ device.
"""

WRITE_MAP = {
    "pOpMode": {
        "command": "0A0112",
        "min": "",
        "max": "",
        "unit": "",
        "step": "",
        "type": "select",
        "device_class": "",
        "icon": "mdi:swap-horizontal",
        "decode_type": "2opmode",
    },
    "p01RoomTempDayHC1": {
        "command": "0B0005",
        "min": "12",
        "max": "32",
        "unit": " °C",
        "step": 0.1,
        "type": "number",
        "device_class": "measurement",
        "icon": "mdi:thermometer",
        "decode_type": "5temp",
    },
    "p02RoomTempNightHC1": {
        "command": "0B0008",
        "min": "12",
        "max": "32",
        "unit": " °C",
        "step": 0.1,
        "type": "number",
        "device_class": "measurement",
        "icon": "mdi:thermometer",
        "decode_type": "5temp",
    },
    "p03RoomTempStandbyHC1": {
        "command": "0B013D",
        "min": "12",
        "max": "32",
        "unit": " °C",
        "step": 0.1,
        "type": "number",
        "device_class": "measurement",
        "icon": "mdi:thermometer",
        "decode_type": "5temp",
    },
    "p01RoomTempDayHC1SummerMode": {
        "command": "0B0569",
        "min": "12",
        "max": "32",
        "unit": " °C",
        "step": 0.1,
        "type": "number",
        "device_class": "measurement",
        "icon": "mdi:thermometer",
        "decode_type": "5temp",
    },
    "p02RoomTempNightHC1SummerMode": {
        "command": "0B056B",
        "min": "12",
        "max": "32",
        "unit": " °C",
        "step": 0.1,
        "type": "number",
        "device_class": "measurement",
        "icon": "mdi:thermometer",
        "decode_type": "5temp",
    },
    "p03RoomTempStandbyHC1SummerMode": {
        "command": "0B056A",
        "min": "12",
        "max": "32",
        "unit": " °C",
        "step": 0.1,
        "type": "number",
        "device_class": "measurement",
        "icon": "mdi:thermometer",
        "decode_type": "5temp",
    },
    "p13GradientHC1": {
        "command": "0B010E",
        "min": "0.1",
        "max": "5",
        "unit": "",
        "step": 0.01,
        "type": "number",
        "device_class": "measurement",
        "icon": "mdi:chart-line",
        "decode_type": "6gradient",
    },
    "p14LowEndHC1": {
        "command": "0B059E",
        "min": "0",
        "max": "10",
        "unit": " K",
        "step": 0.1,
        "type": "number",
        "device_class": "measurement",
        "icon": "mdi:cog",
        "decode_type": "5temp",
    },
    "p15RoomInfluenceHC1": {
        "command": "0B010F",
        "min": "0",
        "max": "100",
        "unit": "%",
        "step": 1,
        "type": "number",
        "device_class": "measurement",
        "icon": "mdi:cog",
        "decode_type": "0clean",
    },
    "p19FlowProportionHC1": {
        "command": "0B059D",
        "min": "0",
        "max": "100",
        "unit": "%",
        "step": 1,
        "type": "number",
        "device_class": "measurement",
        "icon": "mdi:cog",
        "decode_type": "1clean",
    },
    # p20FlowProportionHC2: HC2's counterpart to p19FlowProportionHC1 above.
    # Missing from every firmware map even though the name/translation_key
    # were already scaffolded (entity_translations.py, strings.json) -- the
    # HC2 register block is otherwise a byte-for-byte mirror of HC1's (see
    # p16GradientHC2/p18RoomInfluenceHC2 matching p13GradientHC1/
    # p15RoomInfluenceHC1 at the same offsets one block down), and
    # p17LowEndHC2 sits at 0C059E, exactly where p14LowEndHC1 sits at
    # 0B059E relative to p19FlowProportionHC1's 0B059D -- so 0C059D was a
    # confident guess. Confirmed via the read_raw_register debug service on
    # real hardware (firmware 4.38, LWZ 403 SOL): command 0C059D returned a
    # clean, in-range value (30, i.e. 30%) using the same decode_type as
    # p19 -- not a timeout, not a "not supported" response.
    "p20FlowProportionHC2": {
        "command": "0C059D",
        "min": "0",
        "max": "100",
        "unit": "%",
        "step": 1,
        "type": "number",
        "device_class": "measurement",
        "icon": "mdi:cog",
        "decode_type": "1clean",
    },
    "p01RoomTempDayHC2": {
        "command": "0C0005",
        "min": "12",
        "max": "32",
        "unit": " °C",
        "step": 0.1,
        "type": "number",
        "device_class": "measurement",
        "icon": "mdi:thermometer",
        "decode_type": "5temp",
    },
    "p02RoomTempNightHC2": {
        "command": "0C0008",
        "min": "12",
        "max": "32",
        "unit": " °C",
        "step": 0.1,
        "type": "number",
        "device_class": "measurement",
        "icon": "mdi:thermometer",
        "decode_type": "5temp",
    },
    "p03RoomTempStandbyHC2": {
        "command": "0C013D",
        "min": "12",
        "max": "32",
        "unit": " °C",
        "step": 0.1,
        "type": "number",
        "device_class": "measurement",
        "icon": "mdi:thermometer",
        "decode_type": "5temp",
    },
    "p01RoomTempDayHC2SummerMode": {
        "command": "0C0569",
        "min": "12",
        "max": "32",
        "unit": " °C",
        "step": 0.1,
        "type": "number",
        "device_class": "measurement",
        "icon": "mdi:thermometer",
        "decode_type": "5temp",
    },
    "p02RoomTempNightHC2SummerMode": {
        "command": "0C056B",
        "min": "12",
        "max": "32",
        "unit": " °C",
        "step": 0.1,
        "type": "number",
        "device_class": "measurement",
        "icon": "mdi:thermometer",
        "decode_type": "5temp",
    },
    "p03RoomTempStandbyHC2SummerMode": {
        "command": "0C056A",
        "min": "12",
        "max": "32",
        "unit": " °C",
        "step": 0.1,
        "type": "number",
        "device_class": "measurement",
        "icon": "mdi:thermometer",
        "decode_type": "5temp",
    },
    "p16GradientHC2": {
        "command": "0C010E",
        "min": "0.1",
        "max": "5",
        "unit": "",
        "step": 0.01,
        "type": "number",
        "device_class": "measurement",
        "icon": "mdi:chart-line",
        "decode_type": "6gradient",
    },
    "p17LowEndHC2": {
        "command": "0C059E",
        "min": "0",
        "max": "10",
        "unit": " K",
        "step": 0.1,
        "type": "number",
        "device_class": "measurement",
        "icon": "mdi:cog",
        "decode_type": "5temp",
    },
    "p18RoomInfluenceHC2": {
        "command": "0C010F",
        "min": "0",
        "max": "100",
        "unit": "%",
        "step": 1,
        "type": "number",
        "device_class": "measurement",
        "icon": "mdi:cog",
        "decode_type": "0clean",
    },
    "p04DHWsetDayTemp": {
        "command": "0A0013",
        "min": "10",
        "max": "65",
        "unit": "°C",
        "step": 0.1,
        "type": "number",
        "device_class": "measurement",
        "icon": "mdi:thermometer",
        "decode_type": "5temp",
    },
    "p05DHWsetNightTemp": {
        "command": "0A05BF",
        "min": "10",
        "max": "65",
        "unit": "°C",
        "step": 0.1,
        "type": "number",
        "device_class": "measurement",
        "icon": "mdi:thermometer",
        "decode_type": "5temp",
    },
    "p83DHWsetSolarTemp": {
        "command": "0A05BE",
        "min": "10",
        "max": "75",
        "unit": " °C",
        "step": 0.1,
        "type": "number",
        "device_class": "measurement",
        "icon": "mdi:thermometer",
        "decode_type": "5temp",
    },
    "p06DHWsetStandbyTemp": {
        "command": "0A0581",
        "min": "10",
        "max": "55",
        "unit": " °C",
        "step": 0.1,
        "type": "number",
        "device_class": "measurement",
        "icon": "mdi:thermometer",
        "decode_type": "5temp",
    },
    "p11DHWsetManualTemp": {
        "command": "0A0580",
        "min": "10",
        "max": "55",
        "unit": " °C",
        "step": 0.1,
        "type": "number",
        "device_class": "measurement",
        "icon": "mdi:thermometer",
        "decode_type": "5temp",
    },
    "p36DHWMaxTime": {
        "command": "0A0180",
        "min": "6",
        "max": "12",
        "unit": "",
        "step": 1,
        "type": "number",
        "device_class": "measurement",
        "icon": "mdi:clock-outline",
        "decode_type": "1clean",
    },
    "p07FanStageDay": {
        "command": "0A056C",
        "min": "0",
        "max": "3",
        "unit": "",
        "step": 1,
        "type": "number",
        "device_class": "measurement",
        "icon": "mdi:fan",
        "decode_type": "1clean",
    },
    "p08FanStageNight": {
        "command": "0A056D",
        "min": "0",
        "max": "3",
        "unit": "",
        "step": 1,
        "type": "number",
        "device_class": "measurement",
        "icon": "mdi:fan",
        "decode_type": "1clean",
    },
    "p09FanStageStandby": {
        "command": "0A056F",
        "min": "0",
        "max": "3",
        "unit": "",
        "step": 1,
        "type": "number",
        "device_class": "measurement",
        "icon": "mdi:fan",
        "decode_type": "1clean",
    },
    "p99FanStageParty": {
        "command": "0A0570",
        "min": "0",
        "max": "3",
        "unit": "",
        "step": 1,
        "type": "number",
        "device_class": "measurement",
        "icon": "mdi:fan",
        "decode_type": "1clean",
    },
    "p21Hyst1": {
        "command": "0A05C0",
        "min": "0",
        "max": "10",
        "unit": " K",
        "step": 0.1,
        "type": "number",
        "device_class": "measurement",
        "icon": "mdi:swap-horizontal",
        "decode_type": "5temp",
    },
    "p22Hyst2": {
        "command": "0A05C1",
        "min": "0",
        "max": "10",
        "unit": " K",
        "step": 0.1,
        "type": "number",
        "device_class": "measurement",
        "icon": "mdi:swap-horizontal",
        "decode_type": "5temp",
    },
    "p23Hyst3": {
        "command": "0A05C2",
        "min": "0",
        "max": "5",
        "unit": " K",
        "step": 0.1,
        "type": "number",
        "device_class": "measurement",
        "icon": "mdi:swap-horizontal",
        "decode_type": "5temp",
    },
    "p24Hyst4": {
        "command": "0A05C3",
        "min": "0",
        "max": "5",
        "unit": " K",
        "step": 0.1,
        "type": "number",
        "device_class": "measurement",
        "icon": "mdi:swap-horizontal",
        "decode_type": "5temp",
    },
    "p25Hyst5": {
        "command": "0A05C4",
        "min": "0",
        "max": "5",
        "unit": " K",
        "step": 0.1,
        "type": "number",
        "device_class": "measurement",
        "icon": "mdi:swap-horizontal",
        "decode_type": "5temp",
    },
    "p29HystAsymmetry": {
        "command": "0A05C5",
        "min": "1",
        "max": "5",
        "unit": "",
        "step": 1,
        "type": "number",
        "device_class": "measurement",
        "icon": "mdi:swap-horizontal",
        "decode_type": "1clean",
    },
    "p30integralComponent": {
        "command": "0A0162",
        "min": "10",
        "max": "999",
        "unit": " Kmin",
        "step": 1,
        "type": "number",
        "device_class": "measurement",
        "icon": "mdi:cog",
        "decode_type": "1clean",
    },
    "p31MaxBoosterStgHtg": {
        "command": "0A059F",
        "min": "0",
        "max": "3",
        "unit": "",
        "step": 1,
        "type": "number",
        "device_class": "measurement",
        "icon": "mdi:flash",
        "decode_type": "1clean",
    },
    "p32HystDHW": {
        "command": "0A0140",
        "min": "0",
        "max": "10",
        "unit": " K",
        "step": 0.1,
        "type": "number",
        "device_class": "measurement",
        "icon": "mdi:swap-horizontal",
        "decode_type": "5temp",
    },
    "p33BoosterTimeoutDHW": {
        "command": "0A0588",
        "min": "0",
        "max": "200",
        "unit": " min",
        "step": 1,
        "type": "number",
        "device_class": "measurement",
        "icon": "mdi:clock-outline",
        "decode_type": "1clean",
    },
    "p79BoosterTimeoutHC": {
        "command": "0A05A0",
        "min": "0",
        "max": "60",
        "unit": " min",
        "step": 1,
        "type": "number",
        "device_class": "measurement",
        "icon": "mdi:clock-outline",
        "decode_type": "1clean",
    },
    "p46UnschedVent0": {
        "command": "0A0571",
        "min": "0",
        "max": "1000",
        "unit": " min",
        "step": 1,
        "type": "number",
        "device_class": "measurement",
        "icon": "mdi:air-filter",
        "decode_type": "1clean",
    },
    "p45UnschedVent1": {
        "command": "0A0572",
        "min": "0",
        "max": "1000",
        "unit": " min",
        "step": 1,
        "type": "number",
        "device_class": "measurement",
        "icon": "mdi:air-filter",
        "decode_type": "1clean",
    },
    "p44UnschedVent2": {
        "command": "0A0573",
        "min": "0",
        "max": "1000",
        "unit": " min",
        "step": 1,
        "type": "number",
        "device_class": "measurement",
        "icon": "mdi:air-filter",
        "decode_type": "1clean",
    },
    "p43UnschedVent3": {
        "command": "0A0574",
        "min": "0",
        "max": "1000",
        "unit": " min",
        "step": 1,
        "type": "number",
        "device_class": "measurement",
        "icon": "mdi:air-filter",
        "decode_type": "1clean",
    },
    "p37Fanstage1AirflowInlet": {
        "command": "0A0576",
        "min": "50",
        "max": "300",
        "unit": " m3/h",
        "step": 1,
        "type": "number",
        "device_class": "measurement",
        "icon": "mdi:fan",
        "decode_type": "1clean",
    },
    "p38Fanstage2AirflowInlet": {
        "command": "0A0577",
        "min": "50",
        "max": "300",
        "unit": " m3/h",
        "step": 1,
        "type": "number",
        "device_class": "measurement",
        "icon": "mdi:fan",
        "decode_type": "1clean",
    },
    "p39Fanstage3AirflowInlet": {
        "command": "0A0578",
        "min": "50",
        "max": "300",
        "unit": " m3/h",
        "step": 1,
        "type": "number",
        "device_class": "measurement",
        "icon": "mdi:fan",
        "decode_type": "1clean",
    },
    "p40Fanstage1AirflowOutlet": {
        "command": "0A0579",
        "min": "50",
        "max": "300",
        "unit": " m3/h",
        "step": 1,
        "type": "number",
        "device_class": "measurement",
        "icon": "mdi:fan",
        "decode_type": "1clean",
    },
    "p41Fanstage2AirflowOutlet": {
        "command": "0A057A",
        "min": "50",
        "max": "300",
        "unit": " m3/h",
        "step": 1,
        "type": "number",
        "device_class": "measurement",
        "icon": "mdi:fan",
        "decode_type": "1clean",
    },
    "p42Fanstage3AirflowOutlet": {
        "command": "0A057B",
        "min": "50",
        "max": "300",
        "unit": " m3/h",
        "step": 1,
        "type": "number",
        "device_class": "measurement",
        "icon": "mdi:fan",
        "decode_type": "1clean",
    },
    "p49SummerModeTemp": {
        "command": "0A0116",
        "min": "10",
        "max": "24",
        "unit": " °C",
        "step": 0.1,
        "type": "number",
        "device_class": "measurement",
        "icon": "mdi:thermometer",
        "decode_type": "5temp",
    },
    "p50SummerModeHysteresis": {
        "command": "0A05A2",
        "min": "0.5",
        "max": "5",
        "unit": " K",
        "step": 0.1,
        "type": "number",
        "device_class": "measurement",
        "icon": "mdi:swap-horizontal",
        "decode_type": "5temp",
    },
    "p78DualModePoint": {
        "command": "0A01AC",
        "min": "-10",
        "max": "20",
        "unit": " °C",
        "step": 0.1,
        "type": "number",
        "device_class": "measurement",
        "icon": "mdi:swap-horizontal",
        "decode_type": "5temp",
    },
    "p54MinPumpCycles": {
        "command": "0A05B8",
        "min": "1",
        "max": "24",
        "unit": "",
        "step": 0.1,
        "type": "number",
        "device_class": "measurement",
        "icon": "mdi:pump",
        "decode_type": "1clean",
    },
    "p55MaxPumpCycles": {
        "command": "0A05B7",
        "min": "25",
        "max": "288",
        "unit": "",
        "step": 0.1,
        "type": "number",
        "device_class": "measurement",
        "icon": "mdi:pump",
        "decode_type": "1clean",
    },
    "p56OutTempMaxPumpCycles": {
        "command": "0A05B9",
        "min": "0",
        "max": "20",
        "unit": " °C",
        "step": 0.1,
        "type": "number",
        "device_class": "measurement",
        "icon": "mdi:thermometer",
        "decode_type": "5temp",
    },
    "p57OutTempMinPumpCycles": {
        "command": "0A05BA",
        "min": "0",
        "max": "25",
        "unit": " °C",
        "step": 0.1,
        "type": "number",
        "device_class": "measurement",
        "icon": "mdi:thermometer",
        "decode_type": "5temp",
    },
    "p58SuppressTempCaptPumpStart": {
        "command": "0A0611",
        "min": "0",
        "max": "120",
        "unit": " s",
        "step": 1,
        "type": "number",
        "device_class": "measurement",
        "icon": "mdi:thermometer",
        "decode_type": "1clean",
    },
    "p76RoomThermCorrection": {
        "command": "0A0109",
        "min": "-5",
        "max": "5",
        "unit": " K",
        "step": 0.1,
        "type": "number",
        "device_class": "measurement",
        "icon": "mdi:cog",
        "decode_type": "4temp",
    },
    "p77OutThermFilterTime": {
        "command": "0A010C",
        "min": "1",
        "max": "24",
        "unit": " h",
        "step": 1,
        "type": "number",
        "device_class": "measurement",
        "icon": "mdi:clock-outline",
        "decode_type": "0clean",
    },
    "p35PasteurisationInterval": {
        "command": "0A0586",
        "min": "1",
        "max": "30",
        "unit": "",
        "step": 1,
        "type": "number",
        "device_class": "measurement",
        "icon": "mdi:cog",
        "decode_type": "1clean",
    },
    "p80EnableSolar": {
        "command": "0A03C1",
        "min": "0",
        "max": "1",
        "unit": "",
        "step": 1,
        "type": "number",
        "device_class": "measurement",
        "icon": "mdi:solar-power",
        "decode_type": "1clean",
    },
    "p35PasteurisationTemp": {
        "command": "0A0587",
        "min": "10",
        "max": "65",
        "unit": " °C",
        "step": 0.1,
        "type": "number",
        "device_class": "measurement",
        "icon": "mdi:thermometer",
        "decode_type": "5temp",
    },
    "p34BoosterDHWTempAct": {
        "command": "0A0589",
        "min": "-10",
        "max": "10",
        "unit": " °C",
        "step": 0.1,
        "type": "number",
        "device_class": "measurement",
        "icon": "mdi:thermometer",
        "decode_type": "5temp",
    },
    "p99DHWmaxFlowTemp": {
        "command": "0A058C",
        "min": "10",
        "max": "75",
        "unit": " °C",
        "step": 0.1,
        "type": "number",
        "device_class": "measurement",
        "icon": "mdi:thermometer",
        "decode_type": "5temp",
    },
    "p99HC1maxFlowTemp": {
        "command": "0A0027",
        "min": "10",
        "max": "75",
        "unit": " °C",
        "step": 0.1,
        "type": "number",
        "device_class": "measurement",
        "icon": "mdi:thermometer",
        "decode_type": "5temp",
    },
    "p89DHWeco": {
        "command": "0A058D",
        "min": "0",
        "max": "1",
        "unit": "",
        "step": 1,
        "type": "number",
        "device_class": "measurement",
        "icon": "mdi:cog",
        "decode_type": "1clean",
    },
    "p99startUnschedVent": {
        "command": "0A05DD",
        "min": "0",
        "max": "3",
        "unit": "",
        "step": 1,
        "type": "number",
        "device_class": "measurement",
        "icon": "mdi:air-filter",
        "decode_type": "1clean",
    },
    "p99FrostProtectionBoost": {
        "command": "0A05B3",
        "min": "10",
        "max": "30",
        "unit": " °C",
        "step": 0.1,
        "type": "number",
        "device_class": "measurement",
        "icon": "mdi:cog",
        "decode_type": "5temp",
    },
    "p99FrostProtectionCancel": {
        "command": "0A05B4",
        "min": "0",
        "max": "20",
        "unit": " °C",
        "step": 0.1,
        "type": "number",
        "device_class": "measurement",
        "icon": "mdi:cog",
        "decode_type": "5temp",
    },
    "pClockDay": {
        "command": "0A0122",
        "min": "1",
        "max": "31",
        "unit": "",
        "step": 1,
        "type": "number",
        "device_class": "measurement",
        "icon": "mdi:clock-outline",
        "decode_type": "0clean",
    },
    "pClockMonth": {
        "command": "0A0123",
        "min": "1",
        "max": "12",
        "unit": "",
        "step": 1,
        "type": "number",
        "device_class": "measurement",
        "icon": "mdi:clock-outline",
        "decode_type": "0clean",
    },
    "pClockYear": {
        "command": "0A0124",
        "min": "12",
        "max": "20",
        "unit": "",
        "step": 1,
        "type": "number",
        "device_class": "measurement",
        "icon": "mdi:clock-outline",
        "decode_type": "0clean",
    },
    "pClockHour": {
        "command": "0A0125",
        "min": "0",
        "max": "23",
        "unit": "",
        "step": 1,
        "type": "number",
        "device_class": "measurement",
        "icon": "mdi:clock-outline",
        "decode_type": "0clean",
    },
    "pClockMinutes": {
        "command": "0A0126",
        "min": "0",
        "max": "59",
        "unit": "",
        "step": 1,
        "type": "number",
        "device_class": "measurement",
        "icon": "mdi:clock-outline",
        "decode_type": "0clean",
    },
    "pHolidayBeginDay": {
        "command": "0A011B",
        "min": "1",
        "max": "31",
        "unit": "",
        "step": 1,
        "type": "number",
        "device_class": "measurement",
        "icon": "mdi:beach",
        "decode_type": "0clean",
    },
    "pHolidayBeginMonth": {
        "command": "0A011C",
        "min": "1",
        "max": "12",
        "unit": "",
        "step": 1,
        "type": "number",
        "device_class": "measurement",
        "icon": "mdi:beach",
        "decode_type": "0clean",
    },
    "pHolidayBeginYear": {
        "command": "0A011D",
        "min": "12",
        "max": "30",
        "unit": "",
        "step": 1,
        "type": "number",
        "device_class": "measurement",
        "icon": "mdi:beach",
        "decode_type": "0clean",
    },
    "pHolidayBeginTime": {
        "command": "0A05D3",
        "min": "00:00",
        "max": "23:59",
        "unit": "",
        "step": "",
        "type": "time",
        "device_class": "measurement",
        "icon": "mdi:clock-outline",
        "decode_type": "9holy",
    },
    "pHolidayEndDay": {
        "command": "0A011E",
        "min": "1",
        "max": "31",
        "unit": "",
        "step": 1,
        "type": "number",
        "device_class": "measurement",
        "icon": "mdi:beach",
        "decode_type": "0clean",
    },
    "pHolidayEndMonth": {
        "command": "0A011F",
        "min": "1",
        "max": "12",
        "unit": "",
        "step": 1,
        "type": "number",
        "device_class": "measurement",
        "icon": "mdi:beach",
        "decode_type": "0clean",
    },
    "pHolidayEndYear": {
        "command": "0A0120",
        "min": "12",
        "max": "30",
        "unit": "",
        "step": 1,
        "type": "number",
        "device_class": "measurement",
        "icon": "mdi:beach",
        "decode_type": "0clean",
    },
    "pHolidayEndTime": {
        "command": "0A05D4",
        "min": "00:00",
        "max": "23:59",
        "unit": "",
        "step": "",
        "type": "time",
        "device_class": "measurement",
        "icon": "mdi:clock-outline",
        "decode_type": "9holy",
    },
    "party-time": {
        "command": "0A05D1",
        "min": "00:00",
        "max": "23:59",
        "unit": "",
        "step": "",
        "type": "time",
        "device_class": "measurement",
        "icon": "mdi:calendar-clock",
        "decode_type": "8party",
    },
    "programHC1_Mo_0": {
        "command": "0B1410",
        "min": "00:00",
        "max": "24:00",
        "unit": "",
        "step": "",
        "type": "schedule",
        "device_class": "measurement",
        "icon": "mdi:calendar-clock",
        "decode_type": "7prog",
    },
    "programHC1_Mo_1": {
        "command": "0B1411",
        "min": "00:00",
        "max": "24:00",
        "unit": "",
        "step": "",
        "type": "schedule",
        "device_class": "measurement",
        "icon": "mdi:calendar-clock",
        "decode_type": "7prog",
    },
    "programHC1_Mo_2": {
        "command": "0B1412",
        "min": "00:00",
        "max": "24:00",
        "unit": "",
        "step": "",
        "type": "schedule",
        "device_class": "measurement",
        "icon": "mdi:calendar-clock",
        "decode_type": "7prog",
    },
    "programHC1_Tu_0": {
        "command": "0B1420",
        "min": "00:00",
        "max": "24:00",
        "unit": "",
        "step": "",
        "type": "schedule",
        "device_class": "measurement",
        "icon": "mdi:calendar-clock",
        "decode_type": "7prog",
    },
    "programHC1_Tu_1": {
        "command": "0B1421",
        "min": "00:00",
        "max": "24:00",
        "unit": "",
        "step": "",
        "type": "schedule",
        "device_class": "measurement",
        "icon": "mdi:calendar-clock",
        "decode_type": "7prog",
    },
    "programHC1_Tu_2": {
        "command": "0B1422",
        "min": "00:00",
        "max": "24:00",
        "unit": "",
        "step": "",
        "type": "schedule",
        "device_class": "measurement",
        "icon": "mdi:calendar-clock",
        "decode_type": "7prog",
    },
    "programHC1_We_0": {
        "command": "0B1430",
        "min": "00:00",
        "max": "24:00",
        "unit": "",
        "step": "",
        "type": "schedule",
        "device_class": "measurement",
        "icon": "mdi:calendar-clock",
        "decode_type": "7prog",
    },
    "programHC1_We_1": {
        "command": "0B1431",
        "min": "00:00",
        "max": "24:00",
        "unit": "",
        "step": "",
        "type": "schedule",
        "device_class": "measurement",
        "icon": "mdi:calendar-clock",
        "decode_type": "7prog",
    },
    "programHC1_We_2": {
        "command": "0B1432",
        "min": "00:00",
        "max": "24:00",
        "unit": "",
        "step": "",
        "type": "schedule",
        "device_class": "measurement",
        "icon": "mdi:calendar-clock",
        "decode_type": "7prog",
    },
    "programHC1_Th_0": {
        "command": "0B1440",
        "min": "00:00",
        "max": "24:00",
        "unit": "",
        "step": "",
        "type": "schedule",
        "device_class": "measurement",
        "icon": "mdi:calendar-clock",
        "decode_type": "7prog",
    },
    "programHC1_Th_1": {
        "command": "0B1441",
        "min": "00:00",
        "max": "24:00",
        "unit": "",
        "step": "",
        "type": "schedule",
        "device_class": "measurement",
        "icon": "mdi:calendar-clock",
        "decode_type": "7prog",
    },
    "programHC1_Th_2": {
        "command": "0B1442",
        "min": "00:00",
        "max": "24:00",
        "unit": "",
        "step": "",
        "type": "schedule",
        "device_class": "measurement",
        "icon": "mdi:calendar-clock",
        "decode_type": "7prog",
    },
    "programHC1_Fr_0": {
        "command": "0B1450",
        "min": "00:00",
        "max": "24:00",
        "unit": "",
        "step": "",
        "type": "schedule",
        "device_class": "measurement",
        "icon": "mdi:calendar-clock",
        "decode_type": "7prog",
    },
    "programHC1_Fr_1": {
        "command": "0B1451",
        "min": "00:00",
        "max": "24:00",
        "unit": "",
        "step": "",
        "type": "schedule",
        "device_class": "measurement",
        "icon": "mdi:calendar-clock",
        "decode_type": "7prog",
    },
    "programHC1_Fr_2": {
        "command": "0B1452",
        "min": "00:00",
        "max": "24:00",
        "unit": "",
        "step": "",
        "type": "schedule",
        "device_class": "measurement",
        "icon": "mdi:calendar-clock",
        "decode_type": "7prog",
    },
    "programHC1_Sa_0": {
        "command": "0B1460",
        "min": "00:00",
        "max": "24:00",
        "unit": "",
        "step": "",
        "type": "schedule",
        "device_class": "measurement",
        "icon": "mdi:calendar-clock",
        "decode_type": "7prog",
    },
    "programHC1_Sa_1": {
        "command": "0B1461",
        "min": "00:00",
        "max": "24:00",
        "unit": "",
        "step": "",
        "type": "schedule",
        "device_class": "measurement",
        "icon": "mdi:calendar-clock",
        "decode_type": "7prog",
    },
    "programHC1_Sa_2": {
        "command": "0B1462",
        "min": "00:00",
        "max": "24:00",
        "unit": "",
        "step": "",
        "type": "schedule",
        "device_class": "measurement",
        "icon": "mdi:calendar-clock",
        "decode_type": "7prog",
    },
    "programHC1_So_0": {
        "command": "0B1470",
        "min": "00:00",
        "max": "24:00",
        "unit": "",
        "step": "",
        "type": "schedule",
        "device_class": "measurement",
        "icon": "mdi:calendar-clock",
        "decode_type": "7prog",
    },
    "programHC1_So_1": {
        "command": "0B1471",
        "min": "00:00",
        "max": "24:00",
        "unit": "",
        "step": "",
        "type": "schedule",
        "device_class": "measurement",
        "icon": "mdi:calendar-clock",
        "decode_type": "7prog",
    },
    "programHC1_So_2": {
        "command": "0B1472",
        "min": "00:00",
        "max": "24:00",
        "unit": "",
        "step": "",
        "type": "schedule",
        "device_class": "measurement",
        "icon": "mdi:calendar-clock",
        "decode_type": "7prog",
    },
    "programHC1_Mo-Fr_0": {
        "command": "0B1480",
        "min": "00:00",
        "max": "24:00",
        "unit": "",
        "step": "",
        "type": "schedule",
        "device_class": "measurement",
        "icon": "mdi:calendar-clock",
        "decode_type": "7prog",
    },
    "programHC1_Mo-Fr_1": {
        "command": "0B1481",
        "min": "00:00",
        "max": "24:00",
        "unit": "",
        "step": "",
        "type": "schedule",
        "device_class": "measurement",
        "icon": "mdi:calendar-clock",
        "decode_type": "7prog",
    },
    "programHC1_Mo-Fr_2": {
        "command": "0B1482",
        "min": "00:00",
        "max": "24:00",
        "unit": "",
        "step": "",
        "type": "schedule",
        "device_class": "measurement",
        "icon": "mdi:calendar-clock",
        "decode_type": "7prog",
    },
    "programHC1_Sa-So_0": {
        "command": "0B1490",
        "min": "00:00",
        "max": "24:00",
        "unit": "",
        "step": "",
        "type": "schedule",
        "device_class": "measurement",
        "icon": "mdi:calendar-clock",
        "decode_type": "7prog",
    },
    "programHC1_Sa-So_1": {
        "command": "0B1491",
        "min": "00:00",
        "max": "24:00",
        "unit": "",
        "step": "",
        "type": "schedule",
        "device_class": "measurement",
        "icon": "mdi:calendar-clock",
        "decode_type": "7prog",
    },
    "programHC1_Sa-So_2": {
        "command": "0B1492",
        "min": "00:00",
        "max": "24:00",
        "unit": "",
        "step": "",
        "type": "schedule",
        "device_class": "measurement",
        "icon": "mdi:calendar-clock",
        "decode_type": "7prog",
    },
    "programHC1_Mo-So_0": {
        "command": "0B14A0",
        "min": "00:00",
        "max": "24:00",
        "unit": "",
        "step": "",
        "type": "schedule",
        "device_class": "measurement",
        "icon": "mdi:calendar-clock",
        "decode_type": "7prog",
    },
    "programHC1_Mo-So_1": {
        "command": "0B14A1",
        "min": "00:00",
        "max": "24:00",
        "unit": "",
        "step": "",
        "type": "schedule",
        "device_class": "measurement",
        "icon": "mdi:calendar-clock",
        "decode_type": "7prog",
    },
    "programHC1_Mo-So_2": {
        "command": "0B14A2",
        "min": "00:00",
        "max": "24:00",
        "unit": "",
        "step": "",
        "type": "schedule",
        "device_class": "measurement",
        "icon": "mdi:calendar-clock",
        "decode_type": "7prog",
    },
    "programHC2_Mo_0": {
        "command": "0C1510",
        "min": "00:00",
        "max": "24:00",
        "unit": "",
        "step": "",
        "type": "schedule",
        "device_class": "measurement",
        "icon": "mdi:calendar-clock",
        "decode_type": "7prog",
    },
    "programHC2_Mo_1": {
        "command": "0C1511",
        "min": "00:00",
        "max": "24:00",
        "unit": "",
        "step": "",
        "type": "schedule",
        "device_class": "measurement",
        "icon": "mdi:calendar-clock",
        "decode_type": "7prog",
    },
    "programHC2_Mo_2": {
        "command": "0C1512",
        "min": "00:00",
        "max": "24:00",
        "unit": "",
        "step": "",
        "type": "schedule",
        "device_class": "measurement",
        "icon": "mdi:calendar-clock",
        "decode_type": "7prog",
    },
    "programHC2_Tu_0": {
        "command": "0C1520",
        "min": "00:00",
        "max": "24:00",
        "unit": "",
        "step": "",
        "type": "schedule",
        "device_class": "measurement",
        "icon": "mdi:calendar-clock",
        "decode_type": "7prog",
    },
    "programHC2_Tu_1": {
        "command": "0C1521",
        "min": "00:00",
        "max": "24:00",
        "unit": "",
        "step": "",
        "type": "schedule",
        "device_class": "measurement",
        "icon": "mdi:calendar-clock",
        "decode_type": "7prog",
    },
    "programHC2_Tu_2": {
        "command": "0C1522",
        "min": "00:00",
        "max": "24:00",
        "unit": "",
        "step": "",
        "type": "schedule",
        "device_class": "measurement",
        "icon": "mdi:calendar-clock",
        "decode_type": "7prog",
    },
    "programHC2_We_0": {
        "command": "0C1530",
        "min": "00:00",
        "max": "24:00",
        "unit": "",
        "step": "",
        "type": "schedule",
        "device_class": "measurement",
        "icon": "mdi:calendar-clock",
        "decode_type": "7prog",
    },
    "programHC2_We_1": {
        "command": "0C1531",
        "min": "00:00",
        "max": "24:00",
        "unit": "",
        "step": "",
        "type": "schedule",
        "device_class": "measurement",
        "icon": "mdi:calendar-clock",
        "decode_type": "7prog",
    },
    "programHC2_We_2": {
        "command": "0C1532",
        "min": "00:00",
        "max": "24:00",
        "unit": "",
        "step": "",
        "type": "schedule",
        "device_class": "measurement",
        "icon": "mdi:calendar-clock",
        "decode_type": "7prog",
    },
    "programHC2_Th_0": {
        "command": "0C1540",
        "min": "00:00",
        "max": "24:00",
        "unit": "",
        "step": "",
        "type": "schedule",
        "device_class": "measurement",
        "icon": "mdi:calendar-clock",
        "decode_type": "7prog",
    },
    "programHC2_Th_1": {
        "command": "0C1541",
        "min": "00:00",
        "max": "24:00",
        "unit": "",
        "step": "",
        "type": "schedule",
        "device_class": "measurement",
        "icon": "mdi:calendar-clock",
        "decode_type": "7prog",
    },
    "programHC2_Th_2": {
        "command": "0C1542",
        "min": "00:00",
        "max": "24:00",
        "unit": "",
        "step": "",
        "type": "schedule",
        "device_class": "measurement",
        "icon": "mdi:calendar-clock",
        "decode_type": "7prog",
    },
    "programHC2_Fr_0": {
        "command": "0C1550",
        "min": "00:00",
        "max": "24:00",
        "unit": "",
        "step": "",
        "type": "schedule",
        "device_class": "measurement",
        "icon": "mdi:calendar-clock",
        "decode_type": "7prog",
    },
    "programHC2_Fr_1": {
        "command": "0C1551",
        "min": "00:00",
        "max": "24:00",
        "unit": "",
        "step": "",
        "type": "schedule",
        "device_class": "measurement",
        "icon": "mdi:calendar-clock",
        "decode_type": "7prog",
    },
    "programHC2_Fr_2": {
        "command": "0C1552",
        "min": "00:00",
        "max": "24:00",
        "unit": "",
        "step": "",
        "type": "schedule",
        "device_class": "measurement",
        "icon": "mdi:calendar-clock",
        "decode_type": "7prog",
    },
    "programHC2_Sa_0": {
        "command": "0C1560",
        "min": "00:00",
        "max": "24:00",
        "unit": "",
        "step": "",
        "type": "schedule",
        "device_class": "measurement",
        "icon": "mdi:calendar-clock",
        "decode_type": "7prog",
    },
    "programHC2_Sa_1": {
        "command": "0C1561",
        "min": "00:00",
        "max": "24:00",
        "unit": "",
        "step": "",
        "type": "schedule",
        "device_class": "measurement",
        "icon": "mdi:calendar-clock",
        "decode_type": "7prog",
    },
    "programHC2_Sa_2": {
        "command": "0C1562",
        "min": "00:00",
        "max": "24:00",
        "unit": "",
        "step": "",
        "type": "schedule",
        "device_class": "measurement",
        "icon": "mdi:calendar-clock",
        "decode_type": "7prog",
    },
    "programHC2_So_0": {
        "command": "0C1570",
        "min": "00:00",
        "max": "24:00",
        "unit": "",
        "step": "",
        "type": "schedule",
        "device_class": "measurement",
        "icon": "mdi:calendar-clock",
        "decode_type": "7prog",
    },
    "programHC2_So_1": {
        "command": "0C1571",
        "min": "00:00",
        "max": "24:00",
        "unit": "",
        "step": "",
        "type": "schedule",
        "device_class": "measurement",
        "icon": "mdi:calendar-clock",
        "decode_type": "7prog",
    },
    "programHC2_So_2": {
        "command": "0C1572",
        "min": "00:00",
        "max": "24:00",
        "unit": "",
        "step": "",
        "type": "schedule",
        "device_class": "measurement",
        "icon": "mdi:calendar-clock",
        "decode_type": "7prog",
    },
    "programHC2_Mo-Fr_0": {
        "command": "0C1580",
        "min": "00:00",
        "max": "24:00",
        "unit": "",
        "step": "",
        "type": "schedule",
        "device_class": "measurement",
        "icon": "mdi:calendar-clock",
        "decode_type": "7prog",
    },
    "programHC2_Mo-Fr_1": {
        "command": "0C1581",
        "min": "00:00",
        "max": "24:00",
        "unit": "",
        "step": "",
        "type": "schedule",
        "device_class": "measurement",
        "icon": "mdi:calendar-clock",
        "decode_type": "7prog",
    },
    "programHC2_Mo-Fr_2": {
        "command": "0C1582",
        "min": "00:00",
        "max": "24:00",
        "unit": "",
        "step": "",
        "type": "schedule",
        "device_class": "measurement",
        "icon": "mdi:calendar-clock",
        "decode_type": "7prog",
    },
    "programHC2_Sa-So_0": {
        "command": "0C1590",
        "min": "00:00",
        "max": "24:00",
        "unit": "",
        "step": "",
        "type": "schedule",
        "device_class": "measurement",
        "icon": "mdi:calendar-clock",
        "decode_type": "7prog",
    },
    "programHC2_Sa-So_1": {
        "command": "0C1591",
        "min": "00:00",
        "max": "24:00",
        "unit": "",
        "step": "",
        "type": "schedule",
        "device_class": "measurement",
        "icon": "mdi:calendar-clock",
        "decode_type": "7prog",
    },
    "programHC2_Sa-So_2": {
        "command": "0C1592",
        "min": "00:00",
        "max": "24:00",
        "unit": "",
        "step": "",
        "type": "schedule",
        "device_class": "measurement",
        "icon": "mdi:calendar-clock",
        "decode_type": "7prog",
    },
    "programHC2_Mo-So_0": {
        "command": "0C15A0",
        "min": "00:00",
        "max": "24:00",
        "unit": "",
        "step": "",
        "type": "schedule",
        "device_class": "measurement",
        "icon": "mdi:calendar-clock",
        "decode_type": "7prog",
    },
    "programHC2_Mo-So_1": {
        "command": "0C15A1",
        "min": "00:00",
        "max": "24:00",
        "unit": "",
        "step": "",
        "type": "schedule",
        "device_class": "measurement",
        "icon": "mdi:calendar-clock",
        "decode_type": "7prog",
    },
    "programHC2_Mo-So_2": {
        "command": "0C15A2",
        "min": "00:00",
        "max": "24:00",
        "unit": "",
        "step": "",
        "type": "schedule",
        "device_class": "measurement",
        "icon": "mdi:calendar-clock",
        "decode_type": "7prog",
    },
    "programDHW_Mo_0": {
        "command": "0A1710",
        "min": "00:00",
        "max": "24:00",
        "unit": "",
        "step": "",
        "type": "schedule",
        "device_class": "measurement",
        "icon": "mdi:calendar-clock",
        "decode_type": "7prog",
    },
    "programDHW_Mo_1": {
        "command": "0A1711",
        "min": "00:00",
        "max": "24:00",
        "unit": "",
        "step": "",
        "type": "schedule",
        "device_class": "measurement",
        "icon": "mdi:calendar-clock",
        "decode_type": "7prog",
    },
    "programDHW_Mo_2": {
        "command": "0A1712",
        "min": "00:00",
        "max": "24:00",
        "unit": "",
        "step": "",
        "type": "schedule",
        "device_class": "measurement",
        "icon": "mdi:calendar-clock",
        "decode_type": "7prog",
    },
    "programDHW_Tu_0": {
        "command": "0A1720",
        "min": "00:00",
        "max": "24:00",
        "unit": "",
        "step": "",
        "type": "schedule",
        "device_class": "measurement",
        "icon": "mdi:calendar-clock",
        "decode_type": "7prog",
    },
    "programDHW_Tu_1": {
        "command": "0A1721",
        "min": "00:00",
        "max": "24:00",
        "unit": "",
        "step": "",
        "type": "schedule",
        "device_class": "measurement",
        "icon": "mdi:calendar-clock",
        "decode_type": "7prog",
    },
    "programDHW_Tu_2": {
        "command": "0A1722",
        "min": "00:00",
        "max": "24:00",
        "unit": "",
        "step": "",
        "type": "schedule",
        "device_class": "measurement",
        "icon": "mdi:calendar-clock",
        "decode_type": "7prog",
    },
    "programDHW_We_0": {
        "command": "0A1730",
        "min": "00:00",
        "max": "24:00",
        "unit": "",
        "step": "",
        "type": "schedule",
        "device_class": "measurement",
        "icon": "mdi:calendar-clock",
        "decode_type": "7prog",
    },
    "programDHW_We_1": {
        "command": "0A1731",
        "min": "00:00",
        "max": "24:00",
        "unit": "",
        "step": "",
        "type": "schedule",
        "device_class": "measurement",
        "icon": "mdi:calendar-clock",
        "decode_type": "7prog",
    },
    "programDHW_We_2": {
        "command": "0A1732",
        "min": "00:00",
        "max": "24:00",
        "unit": "",
        "step": "",
        "type": "schedule",
        "device_class": "measurement",
        "icon": "mdi:calendar-clock",
        "decode_type": "7prog",
    },
    "programDHW_Th_0": {
        "command": "0A1740",
        "min": "00:00",
        "max": "24:00",
        "unit": "",
        "step": "",
        "type": "schedule",
        "device_class": "measurement",
        "icon": "mdi:calendar-clock",
        "decode_type": "7prog",
    },
    "programDHW_Th_1": {
        "command": "0A1741",
        "min": "00:00",
        "max": "24:00",
        "unit": "",
        "step": "",
        "type": "schedule",
        "device_class": "measurement",
        "icon": "mdi:calendar-clock",
        "decode_type": "7prog",
    },
    "programDHW_Th_2": {
        "command": "0A1742",
        "min": "00:00",
        "max": "24:00",
        "unit": "",
        "step": "",
        "type": "schedule",
        "device_class": "measurement",
        "icon": "mdi:calendar-clock",
        "decode_type": "7prog",
    },
    "programDHW_Fr_0": {
        "command": "0A1750",
        "min": "00:00",
        "max": "24:00",
        "unit": "",
        "step": "",
        "type": "schedule",
        "device_class": "measurement",
        "icon": "mdi:calendar-clock",
        "decode_type": "7prog",
    },
    "programDHW_Fr_1": {
        "command": "0A1751",
        "min": "00:00",
        "max": "24:00",
        "unit": "",
        "step": "",
        "type": "schedule",
        "device_class": "measurement",
        "icon": "mdi:calendar-clock",
        "decode_type": "7prog",
    },
    "programDHW_Fr_2": {
        "command": "0A1752",
        "min": "00:00",
        "max": "24:00",
        "unit": "",
        "step": "",
        "type": "schedule",
        "device_class": "measurement",
        "icon": "mdi:calendar-clock",
        "decode_type": "7prog",
    },
    "programDHW_Sa_0": {
        "command": "0A1760",
        "min": "00:00",
        "max": "24:00",
        "unit": "",
        "step": "",
        "type": "schedule",
        "device_class": "measurement",
        "icon": "mdi:calendar-clock",
        "decode_type": "7prog",
    },
    "programDHW_Sa_1": {
        "command": "0A1761",
        "min": "00:00",
        "max": "24:00",
        "unit": "",
        "step": "",
        "type": "schedule",
        "device_class": "measurement",
        "icon": "mdi:calendar-clock",
        "decode_type": "7prog",
    },
    "programDHW_Sa_2": {
        "command": "0A1762",
        "min": "00:00",
        "max": "24:00",
        "unit": "",
        "step": "",
        "type": "schedule",
        "device_class": "measurement",
        "icon": "mdi:calendar-clock",
        "decode_type": "7prog",
    },
    "programDHW_So_0": {
        "command": "0A1770",
        "min": "00:00",
        "max": "24:00",
        "unit": "",
        "step": "",
        "type": "schedule",
        "device_class": "measurement",
        "icon": "mdi:calendar-clock",
        "decode_type": "7prog",
    },
    "programDHW_So_1": {
        "command": "0A1771",
        "min": "00:00",
        "max": "24:00",
        "unit": "",
        "step": "",
        "type": "schedule",
        "device_class": "measurement",
        "icon": "mdi:calendar-clock",
        "decode_type": "7prog",
    },
    "programDHW_So_2": {
        "command": "0A1772",
        "min": "00:00",
        "max": "24:00",
        "unit": "",
        "step": "",
        "type": "schedule",
        "device_class": "measurement",
        "icon": "mdi:calendar-clock",
        "decode_type": "7prog",
    },
    "programDHW_Mo-Fr_0": {
        "command": "0A1780",
        "min": "00:00",
        "max": "24:00",
        "unit": "",
        "step": "",
        "type": "schedule",
        "device_class": "measurement",
        "icon": "mdi:calendar-clock",
        "decode_type": "7prog",
    },
    "programDHW_Mo-Fr_1": {
        "command": "0A1781",
        "min": "00:00",
        "max": "24:00",
        "unit": "",
        "step": "",
        "type": "schedule",
        "device_class": "measurement",
        "icon": "mdi:calendar-clock",
        "decode_type": "7prog",
    },
    "programDHW_Mo-Fr_2": {
        "command": "0A1782",
        "min": "00:00",
        "max": "24:00",
        "unit": "",
        "step": "",
        "type": "schedule",
        "device_class": "measurement",
        "icon": "mdi:calendar-clock",
        "decode_type": "7prog",
    },
    "programDHW_Sa-So_0": {
        "command": "0A1790",
        "min": "00:00",
        "max": "24:00",
        "unit": "",
        "step": "",
        "type": "schedule",
        "device_class": "measurement",
        "icon": "mdi:calendar-clock",
        "decode_type": "7prog",
    },
    "programDHW_Sa-So_1": {
        "command": "0A1791",
        "min": "00:00",
        "max": "24:00",
        "unit": "",
        "step": "",
        "type": "schedule",
        "device_class": "measurement",
        "icon": "mdi:calendar-clock",
        "decode_type": "7prog",
    },
    "programDHW_Sa-So_2": {
        "command": "0A1792",
        "min": "00:00",
        "max": "24:00",
        "unit": "",
        "step": "",
        "type": "schedule",
        "device_class": "measurement",
        "icon": "mdi:calendar-clock",
        "decode_type": "7prog",
    },
    "programDHW_Mo-So_0": {
        "command": "0A17A0",
        "min": "00:00",
        "max": "24:00",
        "unit": "",
        "step": "",
        "type": "schedule",
        "device_class": "measurement",
        "icon": "mdi:calendar-clock",
        "decode_type": "7prog",
    },
    "programDHW_Mo-So_1": {
        "command": "0A17A1",
        "min": "00:00",
        "max": "24:00",
        "unit": "",
        "step": "",
        "type": "schedule",
        "device_class": "measurement",
        "icon": "mdi:calendar-clock",
        "decode_type": "7prog",
    },
    "programDHW_Mo-So_2": {
        "command": "0A17A2",
        "min": "00:00",
        "max": "24:00",
        "unit": "",
        "step": "",
        "type": "schedule",
        "device_class": "measurement",
        "icon": "mdi:fan",
        "decode_type": "7prog",
    },
    "programFan_Mo_0": {
        "command": "0A1D10",
        "min": "00:00",
        "max": "24:00",
        "unit": "",
        "step": "",
        "type": "schedule",
        "device_class": "measurement",
        "icon": "mdi:fan",
        "decode_type": "7prog",
    },
    "programFan_Mo_1": {
        "command": "0A1D11",
        "min": "00:00",
        "max": "24:00",
        "unit": "",
        "step": "",
        "type": "schedule",
        "device_class": "measurement",
        "icon": "mdi:fan",
        "decode_type": "7prog",
    },
    "programFan_Mo_2": {
        "command": "0A1D12",
        "min": "00:00",
        "max": "24:00",
        "unit": "",
        "step": "",
        "type": "schedule",
        "device_class": "measurement",
        "icon": "mdi:fan",
        "decode_type": "7prog",
    },
    "programFan_Tu_0": {
        "command": "0A1D20",
        "min": "00:00",
        "max": "24:00",
        "unit": "",
        "step": "",
        "type": "schedule",
        "device_class": "measurement",
        "icon": "mdi:fan",
        "decode_type": "7prog",
    },
    "programFan_Tu_1": {
        "command": "0A1D21",
        "min": "00:00",
        "max": "24:00",
        "unit": "",
        "step": "",
        "type": "schedule",
        "device_class": "measurement",
        "icon": "mdi:fan",
        "decode_type": "7prog",
    },
    "programFan_Tu_2": {
        "command": "0A1D22",
        "min": "00:00",
        "max": "24:00",
        "unit": "",
        "step": "",
        "type": "schedule",
        "device_class": "measurement",
        "icon": "mdi:fan",
        "decode_type": "7prog",
    },
    "programFan_We_0": {
        "command": "0A1D30",
        "min": "00:00",
        "max": "24:00",
        "unit": "",
        "step": "",
        "type": "schedule",
        "device_class": "measurement",
        "icon": "mdi:fan",
        "decode_type": "7prog",
    },
    "programFan_We_1": {
        "command": "0A1D31",
        "min": "00:00",
        "max": "24:00",
        "unit": "",
        "step": "",
        "type": "schedule",
        "device_class": "measurement",
        "icon": "mdi:fan",
        "decode_type": "7prog",
    },
    "programFan_We_2": {
        "command": "0A1D32",
        "min": "00:00",
        "max": "24:00",
        "unit": "",
        "step": "",
        "type": "schedule",
        "device_class": "measurement",
        "icon": "mdi:fan",
        "decode_type": "7prog",
    },
    "programFan_Th_0": {
        "command": "0A1D40",
        "min": "00:00",
        "max": "24:00",
        "unit": "",
        "step": "",
        "type": "schedule",
        "device_class": "measurement",
        "icon": "mdi:fan",
        "decode_type": "7prog",
    },
    "programFan_Th_1": {
        "command": "0A1D41",
        "min": "00:00",
        "max": "24:00",
        "unit": "",
        "step": "",
        "type": "schedule",
        "device_class": "measurement",
        "icon": "mdi:fan",
        "decode_type": "7prog",
    },
    "programFan_Th_2": {
        "command": "0A1D42",
        "min": "00:00",
        "max": "24:00",
        "unit": "",
        "step": "",
        "type": "schedule",
        "device_class": "measurement",
        "icon": "mdi:fan",
        "decode_type": "7prog",
    },
    "programFan_Fr_0": {
        "command": "0A1D50",
        "min": "00:00",
        "max": "24:00",
        "unit": "",
        "step": "",
        "type": "schedule",
        "device_class": "measurement",
        "icon": "mdi:fan",
        "decode_type": "7prog",
    },
    "programFan_Fr_1": {
        "command": "0A1D51",
        "min": "00:00",
        "max": "24:00",
        "unit": "",
        "step": "",
        "type": "schedule",
        "device_class": "measurement",
        "icon": "mdi:fan",
        "decode_type": "7prog",
    },
    "programFan_Fr_2": {
        "command": "0A1D52",
        "min": "00:00",
        "max": "24:00",
        "unit": "",
        "step": "",
        "type": "schedule",
        "device_class": "measurement",
        "icon": "mdi:fan",
        "decode_type": "7prog",
    },
    "programFan_Sa_0": {
        "command": "0A1D60",
        "min": "00:00",
        "max": "24:00",
        "unit": "",
        "step": "",
        "type": "schedule",
        "device_class": "measurement",
        "icon": "mdi:fan",
        "decode_type": "7prog",
    },
    "programFan_Sa_1": {
        "command": "0A1D61",
        "min": "00:00",
        "max": "24:00",
        "unit": "",
        "step": "",
        "type": "schedule",
        "device_class": "measurement",
        "icon": "mdi:fan",
        "decode_type": "7prog",
    },
    "programFan_Sa_2": {
        "command": "0A1D62",
        "min": "00:00",
        "max": "24:00",
        "unit": "",
        "step": "",
        "type": "schedule",
        "device_class": "measurement",
        "icon": "mdi:fan",
        "decode_type": "7prog",
    },
    "programFan_So_0": {
        "command": "0A1D70",
        "min": "00:00",
        "max": "24:00",
        "unit": "",
        "step": "",
        "type": "schedule",
        "device_class": "measurement",
        "icon": "mdi:fan",
        "decode_type": "7prog",
    },
    "programFan_So_1": {
        "command": "0A1D71",
        "min": "00:00",
        "max": "24:00",
        "unit": "",
        "step": "",
        "type": "schedule",
        "device_class": "measurement",
        "icon": "mdi:fan",
        "decode_type": "7prog",
    },
    "programFan_So_2": {
        "command": "0A1D72",
        "min": "00:00",
        "max": "24:00",
        "unit": "",
        "step": "",
        "type": "schedule",
        "device_class": "measurement",
        "icon": "mdi:fan",
        "decode_type": "7prog",
    },
    "programFan_Mo-Fr_0": {
        "command": "0A1D80",
        "min": "00:00",
        "max": "24:00",
        "unit": "",
        "step": "",
        "type": "schedule",
        "device_class": "measurement",
        "icon": "mdi:fan",
        "decode_type": "7prog",
    },
    "programFan_Mo-Fr_1": {
        "command": "0A1D81",
        "min": "00:00",
        "max": "24:00",
        "unit": "",
        "step": "",
        "type": "schedule",
        "device_class": "measurement",
        "icon": "mdi:fan",
        "decode_type": "7prog",
    },
    "programFan_Mo-Fr_2": {
        "command": "0A1D82",
        "min": "00:00",
        "max": "24:00",
        "unit": "",
        "step": "",
        "type": "schedule",
        "device_class": "measurement",
        "icon": "mdi:fan",
        "decode_type": "7prog",
    },
    "programFan_Sa-So_0": {
        "command": "0A1D90",
        "min": "00:00",
        "max": "24:00",
        "unit": "",
        "step": "",
        "type": "schedule",
        "device_class": "measurement",
        "icon": "mdi:fan",
        "decode_type": "7prog",
    },
    "programFan_Sa-So_1": {
        "command": "0A1D91",
        "min": "00:00",
        "max": "24:00",
        "unit": "",
        "step": "",
        "type": "schedule",
        "device_class": "measurement",
        "icon": "mdi:fan",
        "decode_type": "7prog",
    },
    "programFan_Sa-So_2": {
        "command": "0A1D92",
        "min": "00:00",
        "max": "24:00",
        "unit": "",
        "step": "",
        "type": "schedule",
        "device_class": "measurement",
        "icon": "mdi:fan",
        "decode_type": "7prog",
    },
    "programFan_Mo-So_0": {
        "command": "0A1DA0",
        "min": "00:00",
        "max": "24:00",
        "unit": "",
        "step": "",
        "type": "schedule",
        "device_class": "measurement",
        "icon": "mdi:fan",
        "decode_type": "7prog",
    },
    "programFan_Mo-So_1": {
        "command": "0A1DA1",
        "min": "00:00",
        "max": "24:00",
        "unit": "",
        "step": "",
        "type": "schedule",
        "device_class": "measurement",
        "icon": "mdi:fan",
        "decode_type": "7prog",
    },
    "programFan_Mo-So_2": {
        "command": "0A1DA2",
        "min": "00:00",
        "max": "24:00",
        "unit": "",
        "step": "",
        "type": "schedule",
        "device_class": "measurement",
        "icon": "mdi:cog",
        "decode_type": "7prog",
    },
    "pOvenFireplace": {
        "command": "0A057C",
        "min": "0",
        "max": "4",
        "unit": "",
        "step": 1,
        "type": "number",
        "device_class": "measurement",
        "icon": "mdi:cog",
        "decode_type": "1clean",
    },
    "p85MaxDefrostDur": {
        "command": "0A057D",
        "min": "60",
        "max": "250",
        "unit": " min",
        "step": 1,
        "type": "number",
        "device_class": "measurement",
        "icon": "mdi:cog",
        "decode_type": "1clean",
    },
    "p85DefrStartThreshold": {
        "command": "0A057E",
        "min": "0",
        "max": "50",
        "unit": " %",
        "step": 1,
        "type": "number",
        "device_class": "measurement",
        "icon": "mdi:cog",
        "decode_type": "1clean",
    },
    "p85FilterSpeed": {
        "command": "0A057F",
        "min": "0",
        "max": "100",
        "unit": " %",
        "step": 1,
        "type": "number",
        "device_class": "measurement",
        "icon": "mdi:thermometer",
        "decode_type": "1clean",
    },
    "p86OutTempCorrection": {
        "command": "0A05A3",
        "min": "-20",
        "max": "30",
        "unit": "K",
        "step": 0.1,
        "type": "number",
        "device_class": "measurement",
        "icon": "",
        "decode_type": "5temp",
    },
}
